(()=>{
'use strict';
const K='__RISAVE099',V='0.9.9';
const BRIDGE_URL='https://raw.githack.com/sunsee83/open_lab/403e631f2c684c9f789d266924312a0f9bd92b65/bookmarklets/instagram/bridge-stable.svg';
const DB='ri-bookmarklet',STORE='handles',DIRKEY='instagram-download-dir',MODEKEY='riSaveMode',DATAKEY='riMetricsV1';
try{window.__RI_ACTIVE?.destroy?.()}catch{}
for(const k of [K,'__RISAVE098','__RISAVE097','__RISAVE096','__RISAVE095','__RISAVE094','__RISAVE093','__RISAVE092','__RISAVE091','__RISAVE090','__RISAVE089','__RISAVE088','__RISAVE087','__RISAVE086','__RISAVE085','__RISAVE084','__RISAVE083'])try{window[k]?.destroy?.()}catch{}
let sheet,launcher,toast,menu,obs,reelMetrics,dirHandle=null,current=null;
let saveMode=readStorage(MODEKEY)||'default',sheetMode='compact',sheetView='content',detailTab='summary',ensureQueued=false,routeTick='';
const cache=new Map(),metricStore=readJson(DATAKEY,{}),queue=[],pending=new Set();
const inFlight=new Map(),failures=new Map(),controllers=new Set(),timers=new Set(),intervals=new Set(),jobs=new Set(),apiTasks=[];
const CACHE_MS=600000,RETRY_MS=30000;
let destroyed=false,frameId=0,scanEpoch=0,apiActive=0,storageWarning=false;
const researchStore=readJson('riResearchV1',{}),researchBusy=new Set();
let workers=0;
const activity={kind:'',state:'idle',message:'',detail:''};
const safe=s=>String(s||'x').normalize('NFKC').replace(/[\\/:*?"<>|\s]+/g,'_').replace(/^_+|_+$/g,'').slice(0,40)||'x';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const err=e=>`${e?.name||'Error'}: ${e?.message||e||''}`;
const dlIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v11m0 0 4-4m-4 4-4-4M5 18v2h14v-2"/></svg>';
const metricDefs=[['views','조회'],['likes','좋아요'],['comments','댓글'],['reposts','재게시'],['er','ER'],['growth','24h'],['multiple','계정대비'],['date','게시일']];

function readStorage(key){try{return localStorage.getItem(key)}catch{return null}}
function writeStorage(key,value){try{localStorage.setItem(key,value);return true}catch(e){if(!storageWarning){storageWarning=true;queueMicrotask(()=>notify('저장공간에 기록하지 못했습니다. 데이터 내보내기를 사용하세요.'))}return false}}
function abortError(message='작업 취소'){return new DOMException(message,'AbortError')}
function live(){if(destroyed)throw abortError('RI 종료됨')}
function later(fn,ms){const id=setTimeout(()=>{timers.delete(id);if(!destroyed)fn()},ms);timers.add(id);return id}
function every(fn,ms){const id=setInterval(()=>{if(!destroyed)fn()},ms);intervals.add(id);return id}
function freshModel(code){const m=cache.get(code);return m&&Date.now()-m.fetchedAt<CACHE_MS?m:null}
function setHtml(el,html){if(el&&el.__riHtml!==html){el.innerHTML=html;el.__riHtml=html}}
function ownNode(node){const el=node?.nodeType===1?node:node?.parentElement;return !!el?.closest?.('[data-ri-owned],.ri98-card-ui,.ri98-feed,#ri98-sheet,#ri98-reel-metrics,#ri98-menu,#ri98-launcher,#ri98-toast,#ri98-style,#__ri_update_btn')}
function onMutations(records){if(destroyed)return;const relevant=records.some(r=>!ownNode(r.target)&&(r.type==='attributes'||r.type==='characterData'||[...r.addedNodes,...r.removedNodes].some(n=>!ownNode(n))));if(relevant)scheduleEnsure()}
async function request(url,options,read,timeout=20000){live();const c=new AbortController();controllers.add(c);const timer=setTimeout(()=>c.abort(new DOMException('요청 시간초과','TimeoutError')),timeout);try{const r=await fetch(url,{...options,signal:c.signal});if(!r.ok){const e=Error(`HTTP ${r.status}`);e.status=r.status;throw e}const result=await read(r);live();return result}finally{clearTimeout(timer);controllers.delete(c)}}
function apiTask(fn){live();return new Promise((ok,no)=>{apiTasks.push({fn,ok,no});pumpApi()})}
function pumpApi(){while(!destroyed&&apiActive<2&&apiTasks.length){const task=apiTasks.shift();apiActive++;Promise.resolve().then(task.fn).then(task.ok,task.no).finally(()=>{apiActive--;pumpApi()})}}
function mediaIdentity(x){return String(x?.code||x?.shortcode||x?.short_code||'')}
function validItem(x,code){if(!x||typeof x!=='object'||Array.isArray(x))return false;const id=mediaIdentity(x);if(!id||id!==code)return false;return !!(videoUrl(x)||imageUrl(x)||childItems(x).length)}
function observedTime(value){if(value==null||value==='')return 0;const n=Number(value);const t=Number.isFinite(n)?(n<1e12?n*1000:n):Date.parse(value);return Number.isFinite(t)&&t>0?t:0}
function nativeText(root){if(!root)return '';const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let text='',n;while((n=walker.nextNode()))if(!ownNode(n))text+=' '+n.textContent;return text}
function cleanCount(text){const s=String(text||'').trim().replace(/,/g,'');const m=s.match(/^(\d+(?:\.\d+)?)\s*(억|만|천|[KkMm])?$/);if(!m)return undefined;const units={억:1e8,만:1e4,천:1e3,k:1e3,m:1e6};const n=Number(m[1])*(units[(m[2]||'').toLowerCase()]||1);return Number.isFinite(n)?Math.round(n):undefined}
function capturedModel(){const id=currentId();if(!id?.code||current?.code!==id.code)throw Error('현재 콘텐츠를 확인한 뒤 다시 저장해주세요');return current}
function snapshotValid(x){return x&&x.source==='api'&&Number.isFinite(x.t)&&Number.isFinite(x.v)&&x.v>=0}
function captureCaption(m){const c=m.item?.caption;const text=typeof c==='string'?c:c?.text||m.item?.edge_media_to_caption?.edges?.[0]?.node?.text||'';const r=researchStore[m.code]||{};researchStore[m.code]={...r,caption:text,hashtags:[...new Set(text.match(/#[\p{L}\p{N}_]+/gu)||[])],mentions:[...new Set(text.match(/@[A-Za-z0-9_.]+/g)||[])],updatedAt:Date.now()};saveResearch()}
function saveResearch(){writeStorage('riResearchV1',JSON.stringify(researchStore))}

function boxHeader(v,pos,end){if(pos+8>end)throw Error('잘린 MP4 box');let size=v.getUint32(pos),head=8;const type=String.fromCharCode(...new Uint8Array(v.buffer,v.byteOffset+pos+4,4));if(size===1){if(pos+16>end)throw Error('잘린 MP4 확장 box');size=v.getUint32(pos+8)*4294967296+v.getUint32(pos+12);head=16}else if(size===0)size=end-pos;if(!Number.isSafeInteger(size)||size<head||pos+size>end)throw Error('잘못된 MP4 box 크기');return {type,size,head}}
function moovTracks(buffer){const v=new DataView(buffer),tracks=new Set();function walk(start,end,path=[]){for(let p=start;p<end;){const b=boxHeader(v,p,end),next=[...path,b.type];if(b.type==='hdlr'&&path.join('/')==='trak/mdia'&&b.size>=b.head+12){const kind=String.fromCharCode(...new Uint8Array(buffer,p+b.head+8,4));tracks.add(kind)}else if(['trak','mdia'].includes(b.type))walk(p+b.head,p+b.size,next);p+=b.size}}walk(0,v.byteLength);return tracks}
async function inspectMp4(blob){let p=0,ftyp=false,mdat=false,tracks=new Set();while(p<blob.size){const header=await blob.slice(p,p+16).arrayBuffer(),v=new DataView(header);if(v.byteLength<8)throw Error('잘린 MP4 파일');let size=v.getUint32(0),head=8;if(size===1){if(v.byteLength<16)throw Error('잘린 MP4 파일');size=v.getUint32(8)*4294967296+v.getUint32(12);head=16}else if(size===0)size=blob.size-p;const type=String.fromCharCode(...new Uint8Array(header,4,4));if(!Number.isSafeInteger(size)||size<head||p+size>blob.size)throw Error('정상 MP4 파일이 아닙니다');if(type==='ftyp'&&size>=16)ftyp=true;if(type==='mdat'&&size>head)mdat=true;if(type==='moov'){if(size>8*1024*1024)throw Error('MP4 메타데이터가 너무 큽니다');tracks=moovTracks(await blob.slice(p+head,p+size).arrayBuffer())}p+=size}if(!ftyp||!mdat||!tracks.size)throw Error('MP4 미디어 구조를 확인할 수 없습니다');return {video:tracks.has('vide'),audio:tracks.has('soun')}}
async function imageType(blob){const b=new Uint8Array(await blob.slice(0,32).arrayBuffer());if(b[0]===255&&b[1]===216&&b[2]===255)return 'jpg';if(b[0]===137&&String.fromCharCode(...b.slice(1,4))==='PNG')return 'png';if(String.fromCharCode(...b.slice(0,4))==='RIFF'&&String.fromCharCode(...b.slice(8,12))==='WEBP')return 'webp';if(String.fromCharCode(...b.slice(4,8))==='ftyp'&&/avif|avis/.test(String.fromCharCode(...b.slice(8))))return 'avif';throw Error('지원되는 원본 이미지 형식이 아닙니다')}
async function verifiedVideo(m){let last=Error('소리 포함 원본 영상 URL 없음'),expired=false;for(let pass=0;pass<2;pass++){for(const url of [...new Set([...videoVersions(m.item).map(x=>x.url),m.item?.video_url].filter(Boolean))].slice(0,4)){try{const x=await fetchMedia(url),tracks=await inspectMp4(x.blob);if(!tracks.video||!tracks.audio)throw Error('영상과 오디오 트랙이 함께 있는 MP4를 찾지 못했습니다');return x}catch(e){if(e.name==='AbortError')throw e;last=e;if([401,403,404].includes(e.status))expired=true}}if(pass===0&&expired)m=await resolve(m.code,m.kind,true);else break}throw last}
async function batchDestination(name){if(saveMode!=='prompt')return destination(name);if(typeof showDirectoryPicker!=='function')throw Error('일괄 저장은 기본 다운로드 또는 지정 폴더를 선택해주세요');const h=await showDirectoryPicker({mode:'readwrite'});return {kind:'folder',handle:h,label:'이번 저장 폴더'}}
function batchFailure(done,total,errors){const e=Error(`${total}개 중 ${done}개 저장, ${total-done}개 실패${errors[0]?': '+(errors[0].message||errors[0]):''}`);e.name='PartialSaveError';e.done=done;e.failed=total-done;return e}
function researchRecord(){const code=currentId()?.code;return code?researchStore[code]||{}:{}}
function researchButton(action,label,disabled=false){return `<button data-a="${action}" ${disabled?'disabled':''}>${label}</button>`}
function textCard(title,text){return `<section class="ri98-research-card"><b>${esc(title)}</b><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(text||'확인된 내용이 없습니다.')}</p></section>`}
function classifyComment(text){const rules=[['질문',/[?？]|어떻게|어디서|언제|궁금|인가요|나요/],['구매의도',/구매|사고\s?싶|주문|구입|링크|가격|얼마/],['불만',/불만|별로|실망|불량|비싸|안\s?돼|최악/],['반론',/아닌데|아니라|틀렸|반대|하지만/],['긍정',/좋아|좋네|멋|최고|감사|추천|유용/],['팁/정보',/방법|참고|팁|정보|하면\s?돼/]];return rules.filter(([,re])=>re.test(text)).map(([label])=>label)}
function normalizedComment(c){const text=String(c?.text||'').slice(0,20000);if(!text)return null;return {id:String(c.pk||c.id||''),username:String(c.user?.username||''),text,createdAt:observedTime(c.created_at),labels:classifyComment(text),replies:(c.preview_child_comments||c.child_comments||[]).map(x=>({id:String(x.pk||x.id||''),username:String(x.user?.username||''),text:String(x.text||'').slice(0,20000)})).filter(x=>x.text),replyCount:scalarNum(c.child_comment_count)}}
async function collectComments(){const m=capturedModel(),code=m.code,key=code+':comments';if(researchBusy.has(key))return;researchBusy.add(key);const rec=researchStore[code]||(researchStore[code]={}),old=rec.comments;let rows=[],next='',hasMore=false,error='';const seen=new Set();try{const id=String(m.item.pk||m.item.id||'').split('_')[0];if(!/^\d+$/.test(id))throw Error('댓글 조회용 media ID가 없습니다');activitySet('comments','running','댓글 수집 중');const cursors=new Set();for(let page=0;page<10;page++){const j=await sameOriginJson(`/api/v1/media/${id}/comments/?can_support_threading=true&permalink_enabled=false&count=50${next?'&min_id='+encodeURIComponent(next):''}`);if(!Array.isArray(j.comments))throw Error('댓글 응답을 확인할 수 없습니다');for(const c of j.comments){const r=normalizedComment(c),id=r?.id||r?.username+':'+r?.text;if(r&&!seen.has(id)){seen.add(id);rows.push(r)}}hasMore=!!(j.has_more_comments||j.has_more_headload_comments);next=String(j.next_min_id||'');if(rows.length>=500){rows=rows.slice(0,500);hasMore=true;break}if(!hasMore)break;if(!next||cursors.has(next)){error='다음 페이지 정보를 확인할 수 없습니다';break}cursors.add(next)}live()}catch(e){if(e.name==='AbortError')throw e;error=e.message}finally{researchBusy.delete(key)}if(destroyed)return;if(!rows.length&&error&&old)rec.comments={...old,error};else rec.comments={rows,hasMore,error,fetchedAt:Date.now(),replyCoverage:'API 미리보기 답글'};saveResearch();activitySet('comments',error?'error':'success',`댓글 ${rows.length}개 수집`,error||(hasMore?'수집 한도 또는 미수집 페이지가 있습니다':'제공된 댓글 페이지 수집 완료'));renderSheet()}
function analyzeResearch(rec){const caption=String(rec.caption||''),speech=String(rec.stt?.text||''),ocr=String(rec.ocr?.text||''),text=[caption,speech,ocr].filter(Boolean).join('\n');const sentences=text.split(/\n+|(?<=[.!?。！？])\s+/).map(x=>x.trim()).filter(Boolean);return {firstCaption:caption.split(/\n|(?<=[.!?。！？])\s/)[0]||'',speechStart:rec.stt?.chunks?.filter(x=>x.start!=null&&x.start<3).map(x=>x.text).join(' ')||'',cta:[...new Set(sentences.filter(x=>/구매|주문|신청|예약|댓글|저장|공유|팔로우|링크|클릭|프로필|subscribe|follow|click|shop/i.test(x)))].slice(0,30),numbers:[...new Set(text.match(/\d[\d,.]*(?:\s*(?:%|퍼센트|원|만원|억|개|명|분|초|시간|일|개월|년))?/g)||[])].slice(0,60),prices:[...new Set(text.match(/(?:[₩$€]\s*[\d,.]+|\d[\d,.]*\s*(?:만\s?원|천\s?원|원|달러))/g)||[])].slice(0,40)}}
function timeLabel(x){return x==null?'시간 미확인':`${Number(x).toFixed(1)}초`}
function parseTime(s){const parts=String(s).replace(',','.').split(':').map(Number);if(parts.some(x=>!Number.isFinite(x)))return null;return parts.reduce((n,x)=>n*60+x,0)}
function normalizeResearchResult(kind,result){if(!result||typeof result!=='object'||typeof result.text!=='string'||result.text.length>100000)throw Error('인식 결과 형식 또는 크기 오류');const text=result.text;const out={text,source:String(result.source||'import').slice(0,60),at:Date.now()};if(kind==='stt'){out.chunks=(result.chunks||[]).slice(0,2000).map(x=>{const stamp=x.timestamp||[x.start,x.end],num=v=>v==null?null:Number.isFinite(Number(v))&&Number(v)>=0?Number(v):null;return {start:num(stamp[0]),end:num(stamp[1]),text:String(x.text||'').slice(0,10000)}});out.language=String(result.language||'').slice(0,30)}else{out.frames=(result.frames||[]).slice(0,60).map(x=>({time:x.time==null?null:Math.max(0,Number(x.time)||0),text:String(x.text||'').slice(0,10000),width:Number(x.width)||0,height:Number(x.height)||0,lines:(x.lines||[]).slice(0,300).map(l=>({text:String(l.text||'').slice(0,2000),confidence:Number(l.confidence)||0,bbox:l.bbox&&['x0','y0','x1','y1'].every(k=>Number.isFinite(l.bbox[k]))?l.bbox:null}))}));out.coverage=String(result.coverage||'가져온 결과').slice(0,200)}return out}
function parseResearchFile(kind,text,name){if(text.length>1000000)throw Error('1MB 이하 결과 파일을 선택해주세요');if(/\.json$/i.test(name)){const j=JSON.parse(text);return normalizeResearchResult(kind,Array.isArray(j)?{text:j.map(x=>x.text||'').join('\n'),[kind==='stt'?'chunks':'frames']:j}:j)}if(kind==='stt'){const chunks=[];const re=/(\d{1,2}:\d{2}(?::\d{2})?[.,]\d+)\s*-->\s*(\d{1,2}:\d{2}(?::\d{2})?[.,]\d+)[^\n]*\n([\s\S]*?)(?=\n\s*\n|$)/g;let m;while((m=re.exec(text)))chunks.push({start:parseTime(m[1]),end:parseTime(m[2]),text:m[3].replace(/<[^>]*>/g,'').trim()});return normalizeResearchResult(kind,{text:chunks.length?chunks.map(x=>x.text).join('\n'):text.trim(),chunks})}return normalizeResearchResult(kind,{text:text.trim(),frames:[]})}
function importResearch(kind){const m=capturedModel(),input=document.createElement('input');input.type='file';input.hidden=true;input.accept='.txt,.srt,.vtt,.json';input.setAttribute('data-ri-owned','');input.onchange=async()=>{try{const f=input.files?.[0];if(!f)return;const result=parseResearchFile(kind,await f.text(),f.name);live();(researchStore[m.code]||(researchStore[m.code]={}))[kind]=result;saveResearch();renderSheet()}catch(e){if(e.name!=='AbortError')notify(e.message)}finally{input.remove()}};input.oncancel=()=>input.remove();document.documentElement.appendChild(input);input.click()}
async function runResearch(kind){const m=capturedModel(),key=m.code+':'+kind;if(researchBusy.has(key))return;const token=[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join(''),origin=new URL(BRIDGE_URL).origin;const w=window.open(BRIDGE_URL+'?mode=research&origin='+encodeURIComponent(location.origin)+'#'+token,'_blank','width=440,height=360');if(!w)throw Error('분석 창을 허용해주세요');researchBusy.add(key);activitySet(kind,'running',kind==='stt'?'음성 인식 중':'글자 인식 중');let dispose=()=>{},ready=false,payload=null,sent=false;const send=()=>{if(ready&&payload&&!sent){sent=true;w.postMessage({type:'RI_RESEARCH_INPUT',token,kind,...payload},origin)}};try{const resultPromise=new Promise((ok,no)=>{const timer=setTimeout(()=>no(Error('분석 시간초과: 결과 파일 가져오기를 사용할 수 있습니다')),10*60000),poll=setInterval(()=>{if(w.closed)no(abortError('분석 창 닫힘'))},500);const cancel=()=>no(abortError());const on=e=>{const d=e.data;if(e.origin!==origin||e.source!==w||!d||d.token!==token)return;if(d.type==='RI_RESEARCH_READY'){ready=true;send()}else if(d.type==='RI_RESEARCH_RESULT'&&d.kind===kind)try{ok(normalizeResearchResult(kind,d.result))}catch(error){no(error)}else if(d.type==='RI_RESEARCH_ERROR')no(Error(String(d.error||'인식 실패').slice(0,300)))};dispose=()=>{clearTimeout(timer);clearInterval(poll);removeEventListener('message',on);jobs.delete(cancel);try{w.close()}catch{}};jobs.add(cancel);addEventListener('message',on)});resultPromise.catch(()=>{});let item=m.item;if(m.type==='carousel')item=m.children[0];const url=kind==='stt'?(dashAudio(dash(item))||videoUrl(item)):(isVideo(item)?videoUrl(item):imageUrl(item));if(!url)throw Error(kind==='stt'?'음성이 있는 미디어를 선택해주세요':'인식할 원본 이미지 또는 영상이 없습니다');const media=await fetchMedia(url);payload={blob:media.blob,mediaType:isVideo(item)?'video':'photo'};send();const result=await resultPromise;live();(researchStore[m.code]||(researchStore[m.code]={}))[kind]=result;saveResearch();activitySet(kind,'success','인식 완료',result.text?'결과를 확인해주세요':'인식된 텍스트가 없습니다');renderSheet()}catch(e){if(e.name==='AbortError')activityClear();else activitySet(kind,'error','인식 실패',e.message);throw e}finally{dispose();researchBusy.delete(key)}}
async function exportData(format){const name=`RI_${new Date().toISOString().slice(0,10)}.${format}`,chosen=destination(name);let text,type;if(format==='json'){text=JSON.stringify({version:V,exportedAt:new Date().toISOString(),metrics:metricStore,research:researchStore},null,2);type='application/json'}else{const cols=['shortcode','username','postedAt','views','likes','comments','reposts','er','growth','multiple'];const cell=x=>{let s=String(x??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};text='\uFEFF'+[cols,...Object.values(metricStore).map(r=>{const d=deriveMetric(r);return cols.map(k=>r[k]??d[k]??'')})].map(row=>row.map(cell).join(',')).join('\r\n');type='text/csv;charset=utf-8'}await saveBlob(new Blob([text],{type}),name,await chosen)}
function installLoader(U,launch=true){
  if(!['https://www.instagram.com','https://instagram.com','https://m.instagram.com'].includes(location.origin)){alert('Instagram 웹에서 실행해주세요');return}
  const existing=window.__RI_LOADER2;
  if(existing?.url===U){window.__RI_LOADER_REFRESH=existing.refresh;if(launch)existing.launch();return}
  const B='__RI_STABLE_BODY',O=new URL(U).origin;let busy=false;
  function button(show=true){let b=document.getElementById('__ri_update_btn');if(!b){b=document.createElement('button');b.id='__ri_update_btn';b.style.cssText='position:fixed;z-index:2147483647;right:10px;bottom:132px;background:#111;color:white;border:1px solid #777;border-radius:16px;padding:7px 10px;font:12px system-ui';document.documentElement.appendChild(b)}b.style.setProperty('display',show?'block':'none','important');b.textContent='RI 업데이트';b.onclick=refresh;return b}
  function read(){try{return localStorage.getItem(B)||''}catch{return ''}}
  function run(code){return new Promise((ok,no)=>{if(typeof code!=='string'||code.length<100||code.length>524288){no(Error('본체 코드 크기 오류'));return}const version=(code.match(/\bV\s*=\s*['"](\d+\.\d+\.\d+)['"]/)||[])[1];if(!version){no(Error('본체 버전 확인 실패'));return}const before=window.__RI_ACTIVE,s=document.createElement('script'),u=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));let done=false;const finish=e=>{if(done)return;done=true;clearTimeout(timer);s.remove();URL.revokeObjectURL(u);e?no(e):ok()};const timer=setTimeout(()=>finish(Error('본체 실행 시간초과')),6000);s.src=u;s.onload=()=>{const a=window.__RI_ACTIVE;finish(a!==before&&a?.ready&&a.version===version?null:Error('본체가 정상 실행되지 않았습니다'))};s.onerror=()=>finish(Error('브라우저가 본체 실행을 차단했습니다'));try{document.documentElement.appendChild(s)}catch(e){finish(e)}})}
  async function refresh(){if(busy)return;busy=true;let w,cleanup=()=>{};const backup=read();try{const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);const token=[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');w=window.open(U+'?origin='+encodeURIComponent(location.origin)+'#'+token,'_blank','width=360,height=240');if(!w)throw Error('업데이트 창을 허용해주세요');const payload=await new Promise((ok,no)=>{const timer=setTimeout(()=>no(Error('업데이트 시간초과')),30000),poll=setInterval(()=>{if(w.closed)no(Error('업데이트 창이 닫혔습니다'))},500);const on=e=>{const d=e.data;if(e.origin!==O||e.source!==w||!d||d.token!==token)return;if(d.type==='RI_STABLE_ERROR'){no(Error(String(d.error||'업데이트 실패').slice(0,300)));return}if(d.type!=='RI_STABLE_CODE'||d.target!=='current.js'||typeof d.code!=='string'||d.code.length>524288||!/^[0-9a-f]{40}$/i.test(d.sha||''))return;ok(d)};cleanup=()=>{clearTimeout(timer);clearInterval(poll);removeEventListener('message',on)};addEventListener('message',on)});cleanup();w.close();await run(payload.code);localStorage.setItem(B,payload.code);localStorage.setItem('__RI_STABLE_SHA',payload.sha);localStorage.setItem('__RI_STABLE_TARGET','current.js');localStorage.setItem('__RI_STABLE_PROTOCOL','2');button(false)}catch(e){cleanup();try{w?.close()}catch{}if(backup&&!window.__RI_ACTIVE?.ready)try{await run(backup)}catch{}button(true);alert('RI 업데이트 실패: '+(e.message||e))}finally{busy=false}}
  function start(){const code=read();let supported=false;try{supported=localStorage.getItem('__RI_STABLE_PROTOCOL')==='2'}catch{}button(true);if(code&&supported)run(code).then(()=>button(false)).catch(e=>{button(true);alert('RI 실행 실패: '+e.message+' · RI 업데이트를 눌러 복구해주세요')});else refresh()}
  window.__RI_LOADER2={url:U,refresh,launch:start};window.__RI_LOADER_REFRESH=refresh;
  window.__RI_BOOKMARKLET='javascript:('+installLoader.toString()+')('+JSON.stringify(U)+',true)';
  button(false);if(launch)start();
}

function readJson(k,f){try{const x=JSON.parse(readStorage(k)||'');return x&&typeof x==='object'&&!Array.isArray(x)?x:f}catch{return f}}
function writeMetrics(){writeStorage(DATAKEY,JSON.stringify(metricStore))}
function parseHref(h){try{const u=new URL(String(h||''),location.origin||'https://www.instagram.com');if(!/(^|\.)instagram\.com$/i.test(u.hostname))return null;const m=u.pathname.match(/^\/(reels?|p|tv)\/([A-Za-z0-9_-]+)\/?$/i);return m?{kind:/^reels?$/i.test(m[1])?'reel':m[1].toLowerCase(),code:m[2]}:null}catch{return null}}
function routeId(){try{return parseHref(location.pathname)}catch{return null}}
function currentId(){return routeId()||feedTargetId()||gridTargetId()}
function appId(){for(const s of document.querySelectorAll('script[type="application/json"]')){const m=(s.textContent||'').match(/"APP_ID":"?(\d+)"?/i);if(m)return m[1]}return'936619743392459'}
async function sameOriginJson(url){return apiTask(()=>request(url,{credentials:'include',cache:'no-store',headers:{'X-IG-App-ID':appId(),'Accept':'application/json'}},r=>r.json()))}
function normalizeItem(x,code){
  const q=[{x,d:0}],seen=new Set();
  while(q.length){const {x:v,d}=q.shift();if(!v||typeof v!=='object'||seen.has(v)||d>5)continue;seen.add(v);if(validItem(v,code))return v;
    for(const key of ['data','graphql','xdt_api__v1__media__shortcode__web_info','xdt_shortcode_media','shortcode_media','items','node','media']){const child=v[key];if(Array.isArray(child))for(const item of child.slice(0,30))q.push({x:item,d:d+1});else if(child)q.push({x:child,d:d+1})}
  }return null;
}
function usernameOf(i){return i?.user?.username||i?.owner?.username||i?.owner?.user?.username||i?.username||'unknown'}
function childItems(i){if(Array.isArray(i?.carousel_media))return i.carousel_media;if(Array.isArray(i?.edge_sidecar_to_children?.edges))return i.edge_sidecar_to_children.edges.map(e=>e?.node).filter(Boolean);if(Array.isArray(i?.children))return i.children;return[]}
function videoVersions(i){const a=Array.isArray(i?.video_versions)?i.video_versions:[],b=Array.isArray(i?.video_resources)?i.video_resources.map(x=>({url:x.src,width:x.config_width||x.width,height:x.config_height||x.height})):[];return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function videoUrl(i){return videoVersions(i)[0]?.url||i?.video_url||''}
function imageCandidates(i){const a=Array.isArray(i?.image_versions2?.candidates)?i.image_versions2.candidates:[],b=[];if(i?.display_url)b.push({url:i.display_url,width:i.dimensions?.width,height:i.dimensions?.height});if(i?.display_resources)for(const x of i.display_resources)b.push({url:x.src,width:x.config_width,height:x.config_height});return[...a,...b].filter(x=>x?.url).sort((x,y)=>((y.width||0)*(y.height||0))-((x.width||0)*(x.height||0)))}
function imageUrl(i){return imageCandidates(i)[0]?.url||''}
function explicitCover(i){return i?.cover_frame_url||i?.cover_url||i?.clips_metadata?.cover_frame_url||i?.clips_metadata?.cover_media?.image_versions2?.candidates?.[0]?.url||''}
function isVideo(i){return !!(videoUrl(i)||i?.is_video||Number(i?.media_type)===2||/video|clips|reel/i.test(String(i?.product_type||i?.__typename||'')))}
function mediaType(i){const ch=childItems(i);if(ch.length>1||Number(i?.media_type)===8||/sidecar/i.test(String(i?.__typename||'')))return'carousel';return isVideo(i)?'video':'photo'}
function dash(i){return i?.video_dash_manifest||i?.dash_info?.video_dash_manifest||''}
function dashAudio(xml){if(!xml)return'';try{const doc=new DOMParser().parseFromString(xml,'application/xml'),xs=[...doc.querySelectorAll('Representation')].map(rep=>{const a=rep.closest('AdaptationSet'),mime=rep.getAttribute('mimeType')||a?.getAttribute('mimeType')||'',type=a?.getAttribute('contentType')||'',bw=+(rep.getAttribute('bandwidth')||0),url=rep.querySelector('BaseURL')?.textContent?.trim()||'';return{mime,type,bw,url}}).filter(x=>x.url&&(x.mime.startsWith('audio')||x.type==='audio'));return xs.sort((a,b)=>b.bw-a.bw)[0]?.url||''}catch{return''}}
function scalarNum(x){if(x&&typeof x==='object')x=x.count??x.value;if(x==null||typeof x==='boolean'||typeof x==='object'||String(x).trim()==='')return undefined;const n=Number(x);return Number.isFinite(n)&&n>=0?n:undefined}
function metricDeep(root,keys,code){
  const q=[{v:root,d:0}],seen=new Set();
  while(q.length){const {v,d}=q.shift();if(!v||typeof v!=='object'||seen.has(v)||d>3)continue;seen.add(v);const id=mediaIdentity(v);if(id&&id!==code)continue;
    for(const k of keys){const n=scalarNum(v[k]);if(n!==undefined)return n}
    // Only metric containers belonging to this media. Never search comments, owner, or carousel children.
    for(const k of ['metrics','statistics','insights','counts','clips_metadata','media','node']){const child=v[k];if(child&&typeof child==='object'&&!Array.isArray(child))q.push({v:child,d:d+1})}
  }return undefined;
}
function itemDate(item,code){const t=observedTime(item?.taken_at??item?.taken_at_timestamp??item?.date??item?.created_at??metricDeep(item,['taken_at','taken_at_timestamp','takenAt'],code));return t?new Date(t).toISOString().slice(0,10):''}
function metricFromItem(item,code,kind){const now=Date.now();return {shortcode:code,username:usernameOf(item),type:mediaType(item),kind,postedAt:itemDate(item,code),postedAtMs:observedTime(item?.taken_at??item?.taken_at_timestamp??item?.date??item?.created_at),apiAt:now,updatedAt:now,source:'api',views:metricDeep(item,['play_count','ig_play_count','video_play_count','video_view_count','view_count','clips_play_count','reel_view_count','media_view_count','views','plays'],code),likes:metricDeep(item,['like_count','likes_count','likes','likeCount','edge_media_preview_like','edge_liked_by'],code),comments:metricDeep(item,['comment_count','comments_count','comments','commentCount','edge_media_to_comment','edge_media_to_parent_comment'],code),reposts:metricDeep(item,['repost_count','reshare_count','reposts_count','reposts','repostCount'],code)}}
function persistMetric(rec){
  if(destroyed||!rec?.shortcode)return null;
  const old=metricStore[rec.shortcode]||{shortcode:rec.shortcode},next=old.schema===2?{...old,sources:{...old.sources}}:{shortcode:rec.shortcode,schema:2,sources:{}};
  for(const k of ['username','type','kind','postedAt','postedAtMs','updatedAt','apiAt','nativeAt'])if(rec[k]!==undefined&&rec[k]!==''&&rec[k]!=='unknown'&&rec[k]!==0)next[k]=rec[k];
  for(const k of ['views','likes','comments','reposts']){const n=scalarNum(rec[k]);if(n===undefined)continue;if(rec.source==='native'&&next[k]!==undefined&&next.sources[k]?.source!=='native')continue;next[k]=n;next.sources[k]={source:rec.source||'unknown',at:rec.apiAt||rec.nativeAt||Date.now()}}
  next.history=(Array.isArray(old.history)?old.history:[]).filter(snapshotValid).filter(x=>Date.now()-x.t<=14*86400000);
  if(rec.source==='api'&&scalarNum(rec.views)!==undefined){const now=Number(rec.apiAt)||Date.now(),last=next.history.at(-1);next.viewsAt=now;if(!last||now-last.t>=1800000||last.v!==rec.views)next.history.push({t:now,v:rec.views,source:'api'})}
  next.history=next.history.slice(-700);metricStore[rec.shortcode]=next;writeMetrics();return next;
}
function deriveMetric(rec){
  if(!rec)return {};const views=scalarNum(rec.views);let er,growth,multiple;
  if(views>0&&['likes','comments','reposts'].every(k=>scalarNum(rec[k])!==undefined))er=(Number(rec.likes)+Number(rec.comments)+Number(rec.reposts))/views*100;
  const at=Number(rec.viewsAt)||0;let best=null,delta=Infinity;
  if(at&&Date.now()-at<CACHE_MS)for(const x of rec.history||[]){if(!snapshotValid(x)||x.v<=0)continue;const age=at-x.t;if(age<18*3600000||age>32*3600000)continue;const d=Math.abs(age-24*3600000);if(d<delta){delta=d;best=x}}
  if(best&&views>=best.v)growth=(views-best.v)/best.v*100;
  const owner=String(rec.username||'').toLowerCase();
  if(owner&&owner!=='unknown'&&views>0){const posted=x=>Number(x.postedAtMs)||Date.parse(x.postedAt)||0;const list=Object.values(metricStore).filter(x=>x&&x.schema===2&&x.shortcode!==rec.shortcode&&String(x.username||'').toLowerCase()===owner&&scalarNum(x.views)>0&&posted(x)>0).sort((a,b)=>posted(b)-posted(a)).slice(0,20);if(list.length>=5){const values=list.map(x=>Number(x.views)).sort((a,b)=>a-b),mid=Math.floor(values.length/2),median=values.length%2?values[mid]:(values[mid-1]+values[mid])/2;if(median>0)multiple=views/median}}
  return {er,growth,multiple};
}
function fmtCount(v){if(v===undefined||v===null||v==='')return'';const n=Number(v);if(!Number.isFinite(n)||n<0)return'';if(n>=1e8)return`${(n/1e8).toFixed(n>=1e9?0:1).replace(/\.0$/,'')}억`;if(n>=1e4)return`${(n/1e4).toFixed(n>=1e5?0:1).replace(/\.0$/,'')}만`;if(n>=1e3)return`${(n/1e3).toFixed(n>=1e4?0:1).replace(/\.0$/,'')}K`;return String(Math.round(n))}
function fmtPct(v,sign=false){if(v===undefined||!Number.isFinite(Number(v)))return'';const n=Number(v),s=(sign&&n>0)?'+':'';return`${s}${(Math.abs(n)>=10?n.toFixed(1):n.toFixed(2)).replace(/0+$/,'').replace(/\.$/,'')}%`}
function fmtMul(v){return v!==undefined&&Number.isFinite(Number(v))&&Number(v)>0?`×${Number(v).toFixed(Number(v)>=10?1:2).replace(/0+$/,'').replace(/\.$/,'')}`:''}
function shortDate(v){return /^\d{4}-\d{2}-\d{2}/.test(String(v||''))?String(v).slice(5,10).replace('-','/'):''}
function parseCompactCount(text){return cleanCount(text)}
function buttonMetric(root,terms){if(!root)return undefined;for(const b of root.querySelectorAll('button,[role="button"]')){if(ownNode(b))continue;const label=(b.getAttribute('aria-label')||'')+' '+[...b.querySelectorAll('svg')].map(x=>x.getAttribute('aria-label')||'').join(' ');if(!terms.some(t=>label.toLowerCase().includes(t)))continue;
  for(const text of [b.textContent,label.replace(/좋아요\s*취소|좋아요|댓글|재게시|unlike|likes?|comments?|reposts?/gi,'').trim()]){const n=cleanCount(text);if(n!==undefined)return n}
  const p=b.parentElement;if(p&&p.querySelectorAll('button,[role="button"]').length===1){const n=cleanCount(nativeText(p));if(n!==undefined)return n}
}return undefined}
function textMetric(root,patterns){const txt=[...root.querySelectorAll('a[href*="/liked_by"],a[href*="/comments"]')].filter(x=>!ownNode(x)).map(nativeText).join(' ');for(const re of patterns){const m=txt.match(re);if(m){const n=cleanCount(m[1]);if(n!==undefined)return n}}return undefined}
function nativeMetrics(root){if(!root)return{};const likes=buttonMetric(root,['좋아요','like','unlike'])??textMetric(root,[/좋아요\s*([\d,.]+\s*(?:만|천|억|[KkMm])?)/i,/([\d,.]+\s*(?:만|천|억|[KkMm])?)\s*likes?/i]);const comments=buttonMetric(root,['댓글','comment'])??textMetric(root,[/댓글\s*([\d,.]+\s*(?:만|천|억|[KkMm])?)/i,/([\d,.]+\s*(?:만|천|억|[KkMm])?)\s*comments?/i]);const reposts=buttonMetric(root,['재게시','repost'])??textMetric(root,[/재게시\s*([\d,.]+\s*(?:만|천|억|[KkMm])?)/i,/([\d,.]+\s*(?:만|천|억|[KkMm])?)\s*reposts?/i]);const time=root.querySelector('time[datetime]')?.getAttribute('datetime')||'';let postedAt='';if(time){const d=new Date(time);if(!Number.isNaN(d.getTime()))postedAt=d.toISOString().slice(0,10)}return{likes,comments,reposts,postedAt}}
function mergeNative(code,root){if(destroyed||!code||!root||ownNode(root))return;const now=Date.now(),stored=metricStore[code],old=stored?.schema===2?stored:{};if(now-(old.nativeAt||0)<3000)return;const n=nativeMetrics(root),patch={shortcode:code,nativeAt:now,source:'native'};for(const k of ['likes','comments','reposts'])if(n[k]!==undefined&&(old[k]===undefined||old.sources?.[k]?.source==='native'))patch[k]=n[k];if(n.postedAt&&!old.postedAt)patch.postedAt=n.postedAt;if(Object.keys(patch).length>3)persistMetric(patch)}
async function resolve(code,kind='p',force=false){
  live();if(!/^[A-Za-z0-9_-]+$/.test(code||''))throw Error('올바른 shortcode 없음');
  const cached=freshModel(code);if(!force&&cached)return cached;if(inFlight.has(code))return inFlight.get(code);
  const failed=failures.get(code);if(!force&&failed&&Date.now()-failed.at<RETRY_MS)throw failed.error;
  const task=(async()=>{let item=null,last=null;const vars=encodeURIComponent(JSON.stringify({shortcode:code}));const urls=[`/graphql/query/?query_id=9496392173716084&variables=${vars}`,`/graphql/query/?query_hash=2c4c2e343a8f64c625ba02b2aa12c7f8&variables=${vars}`,`/${kind==='reel'?'reel':'p'}/${encodeURIComponent(code)}/?__a=1&__d=dis`];
    for(const url of urls){try{const j=await sameOriginJson(url);item=normalizeItem(j,code);if(item)break;last=Error('콘텐츠 구조 또는 shortcode 불일치')}catch(e){if(destroyed||e.name==='AbortError')throw e;last=e;if([401,403,429].includes(e.status))break}}
    live();if(!item)throw last||Error('콘텐츠 원본 정보 없음');const m={code,kind,item,username:usernameOf(item),type:mediaType(item),children:childItems(item),fetchedAt:Date.now()};cache.set(code,m);failures.delete(code);persistMetric(metricFromItem(item,code,kind));captureCaption(m);refreshVisibleMetrics();return m;
  })();inFlight.set(code,task);try{return await task}catch(error){if(!destroyed&&error.name!=='AbortError')failures.set(code,{at:Date.now(),error});throw error}finally{if(inFlight.get(code)===task)inFlight.delete(code)}
}
async function resolveCurrent(force=false){const id=currentId(),epoch=++scanEpoch;if(!id?.code){current=null;renderSheet();throw Error('현재 콘텐츠 shortcode를 찾지 못함')}if(current?.code!==id.code){current=null;renderSheet()}const m=await resolve(id.code,id.kind,force);live();if(epoch!==scanEpoch||currentId()?.code!==id.code)throw abortError('화면이 변경되었습니다');current=m;renderSheet();refreshVisibleMetrics();return m}
function base(m){return`IG_${safe(m?.code)}`}
function ext(type,url=''){type=String(type||'').toLowerCase();if(type.includes('png')||/\.png(?:[?#]|$)/i.test(url))return'png';if(type.includes('webp')||/\.webp(?:[?#]|$)/i.test(url))return'webp';if(type.includes('avif')||/\.avif(?:[?#]|$)/i.test(url))return'avif';return'jpg'}
function names(m){return{video:`${base(m)}.mp4`,audio:`${base(m)}_a.m4a`,frame:`${base(m)}_f.jpg`}}
async function fetchMedia(url){if(!url)throw Error('원본 URL 없음');const u=new URL(url,location.href);if(u.protocol!=='https:')throw Error('안전한 미디어 URL이 아닙니다');return request(u.href,{credentials:'omit',mode:'cors',cache:'no-cache'},async r=>{const size=Number(r.headers.get('content-length'));if(size>256*1024*1024)throw Error('256MB 이하 파일만 저장할 수 있습니다');const blob=await r.blob();if(!blob.size||blob.size>256*1024*1024)throw Error('파일 크기를 확인해주세요');return {blob,type:blob.type||r.headers.get('content-type')||'',url}},60000)}
function openDb(){return new Promise((ok,no)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function idbPut(k,v){const db=await openDb();try{await new Promise((ok,no)=>{const tx=db.transaction(STORE,'readwrite');tx.oncomplete=ok;tx.onerror=()=>no(tx.error);tx.onabort=()=>no(tx.error||Error('폴더 저장 취소'));tx.objectStore(STORE).put(v,k)})}finally{db.close()}}
async function idbGet(k){const db=await openDb();try{return await new Promise((ok,no)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(k);q.onsuccess=()=>ok(q.result||null);q.onerror=()=>no(q.error)})}finally{db.close()}}
async function restoreDir(){try{const handle=await idbGet(DIRKEY);if(!destroyed){dirHandle=handle;renderSheet()}}catch{}}
async function chooseDir(){if(typeof showDirectoryPicker!=='function')throw Error('지정 폴더 저장 미지원');dirHandle=await showDirectoryPicker({mode:'readwrite'});await idbPut(DIRKEY,dirHandle);saveMode='folder';writeStorage(MODEKEY,saveMode);renderSheet()}
function setMode(mode){if(mode==='prompt'&&typeof showSaveFilePicker!=='function')throw Error('매번 선택 저장 미지원');saveMode=mode;writeStorage(MODEKEY,mode);renderSheet()}
async function writableDir(){if(!dirHandle)throw Error('저장 폴더를 먼저 지정하세요');let p=typeof dirHandle.queryPermission==='function'?await dirHandle.queryPermission({mode:'readwrite'}):'granted';if(p!=='granted'&&typeof dirHandle.requestPermission==='function')p=await dirHandle.requestPermission({mode:'readwrite'});if(p!=='granted')throw Error('폴더 쓰기 권한 필요');return dirHandle}
async function destination(name){if(saveMode==='folder'){const h=await writableDir();return{kind:'folder',handle:h,label:`지정 폴더/${h.name||''}`}}if(saveMode==='prompt'){const h=await showSaveFilePicker({suggestedName:name});return{kind:'file',handle:h,label:'직접 선택'}}return{kind:'default',label:'기본 다운로드'}}
async function saveBlob(blob,name,dest){live();dest=dest||await destination(name);live();if(dest.kind==='folder'||dest.kind==='file'){const f=dest.kind==='folder'?await dest.handle.getFileHandle(name,{create:true}):dest.handle;if(dest.kind==='file'){const wanted=name.match(/\.([^.]+)$/)?.[1],actual=f.name?.match(/\.([^.]+)$/)?.[1]?.toLowerCase();if(wanted&&actual&&actual!==wanted&&!(wanted==='jpg'&&actual==='jpeg'))throw Error(`원본 형식은 ${wanted.toUpperCase()}입니다. 파일 확장자를 맞춰 다시 선택해주세요`)}live();const w=await f.createWritable();try{live();await w.write(blob);live();await w.close()}catch(e){try{await w.abort()}catch{}throw e}return dest.label}const u=URL.createObjectURL(blob),a=document.createElement('a');a.setAttribute('data-ri-owned','');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),12000);return dest.label}
async function firstFrame(url){const x=await fetchMedia(url),u=URL.createObjectURL(x.blob),v=document.createElement('video');v.setAttribute('data-ri-owned','');v.muted=true;v.playsInline=true;v.preload='auto';v.style='position:fixed;left:-9999px;top:-9999px;width:2px;height:2px';document.body.appendChild(v);function wait(event,start,ms){return new Promise((ok,no)=>{const done=e=>{clearTimeout(to);v.removeEventListener(event,good);v.removeEventListener('error',bad);e?no(e):ok()},good=()=>done(),bad=()=>done(Error('영상 프레임 로드 실패')),to=setTimeout(()=>done(Error('프레임 로드 시간초과')),ms);v.addEventListener(event,good,{once:true});v.addEventListener('error',bad,{once:true});start()})}try{await wait('loadeddata',()=>{v.src=u;v.load()},12000);live();v.pause();if(v.currentTime!==0)await wait('seeked',()=>v.currentTime=0,4000);live();if(!v.videoWidth||!v.videoHeight)throw Error('영상 크기 확인 실패');const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return await new Promise((ok,no)=>c.toBlob(b=>b?ok(b):no(Error('JPG 생성 실패')),'image/jpeg',.95))}finally{v.removeAttribute('src');v.load();v.remove();URL.revokeObjectURL(u)}}
async function model(m){live();if(m)return m;const id=currentId();if(!id?.code)throw Error('현재 콘텐츠 없음');if(current?.code===id.code&&freshModel(id.code))return current;return resolveCurrent()}
function activitySet(kind,state,message,detail=''){if(destroyed)return;activity.kind=kind;activity.state=state;activity.message=message;activity.detail=detail;renderSheet()}
function activityClear(){activity.kind='';activity.state='idle';activity.message='';activity.detail='';renderSheet()}
async function saveVideo(m,dest){m=m||capturedModel();const chosen=dest?Promise.resolve(dest):destination(names(m).video);activitySet('video','running','영상 저장 중');try{const d=await chosen,x=await verifiedVideo(m),name=names(m).video,where=await saveBlob(x.blob,name,d);activitySet('video','success','영상 저장 완료',`${name} · 오디오 포함 · ${where}`);return name}catch(e){if(e.name==='AbortError')activityClear();else activitySet('video','error','영상 저장 실패',err(e));throw e}}
async function saveAudio(m,dest){m=m||capturedModel();const name=names(m).audio,chosen=dest?Promise.resolve(dest):destination(name);activitySet('audio','running','음원 저장 중');try{const d=await chosen,url=dashAudio(dash(m.item));if(!url)throw Error('별도 음원 URL 없음');const x=await fetchMedia(url),tracks=await inspectMp4(x.blob);if(!tracks.audio||tracks.video)throw Error('분리 오디오 파일이 아닙니다');const where=await saveBlob(x.blob,name,d);activitySet('audio','success','음원 저장 완료',`${name} · ${where}`);return name}catch(e){if(e.name==='AbortError')activityClear();else activitySet('audio','error','음원 저장 실패',err(e));throw e}}
async function saveImage(m,dest){m=m||capturedModel();const cover=explicitCover(m.item),suggested=cover?`${base(m)}_c.${ext('',cover)}`:names(m).frame,chosen=dest?Promise.resolve(dest):destination(suggested);activitySet('image','running','이미지 저장 중');try{const d=await chosen;let blob,name;if(cover){const x=await fetchMedia(cover);blob=x.blob;name=`${base(m)}_c.${await imageType(blob)}`}else{blob=await firstFrame(videoUrl(m.item));name=names(m).frame}const where=await saveBlob(blob,name,d);activitySet('image','success','이미지 저장 완료',`${name} · ${cover?'실제 표지':'0.000초'} · ${where}`);return name}catch(e){if(e.name==='AbortError')activityClear();else activitySet('image','error','이미지 저장 실패',err(e));throw e}}
async function savePhoto(m,dest){m=m||capturedModel();const url=imageUrl(m.item),chosen=dest?Promise.resolve(dest):destination(`${base(m)}.${ext('',url)}`);activitySet('photo','running','사진 저장 중');try{const d=await chosen,x=await fetchMedia(url),name=`${base(m)}.${await imageType(x.blob)}`,where=await saveBlob(x.blob,name,d);activitySet('photo','success','사진 저장 완료',`${name} · ${where}`);return name}catch(e){if(e.name==='AbortError')activityClear();else activitySet('photo','error','사진 저장 실패',err(e));throw e}}
async function saveCarousel(m){m=m||capturedModel();const chosen=batchDestination(`${base(m)}_01.jpg`);activitySet('carousel','running','슬라이드 저장 중');try{const dest=await chosen,ch=m.children?.length?m.children:childItems(m.item);if(!ch.length)throw Error('슬라이드 항목 없음');let done=0;const errors=[];for(let i=0;i<ch.length;i++){live();try{const child=ch[i],vid=isVideo(child),x=vid?await verifiedVideo({code:mediaIdentity(child)||m.code,kind:m.kind,item:child}):await fetchMedia(imageUrl(child)),suffix=vid?'mp4':await imageType(x.blob),name=`${base(m)}_${String(i+1).padStart(2,'0')}.${suffix}`;await saveBlob(x.blob,name,dest);done++;activitySet('carousel','running',`슬라이드 저장 ${done}/${ch.length}`)}catch(e){if(e.name==='AbortError')throw e;errors.push(e)}}if(errors.length)throw batchFailure(done,ch.length,errors);activitySet('carousel','success',`슬라이드 ${done}개 완료`);return {done,failed:0}}catch(e){if(e.name==='AbortError')activityClear();else activitySet('carousel','error','슬라이드 저장 실패',err(e));throw e}}
async function saveVideoSet(m){m=m||capturedModel();const chosen=batchDestination(names(m).video),dest=await chosen,jobs=[()=>saveVideo(m,dest),()=>saveAudio(m,dest),()=>saveImage(m,dest)],out=[],errors=[];for(const fn of jobs){live();try{out.push(await fn())}catch(e){if(e.name==='AbortError')throw e;errors.push(e)}}if(errors.length){const e=batchFailure(out.length,3,errors);activitySet('all3','error',`3개 저장 ${out.length}/3`,e.message);throw e}activitySet('all3','success','3개 저장 3/3','완료');return out}
function metricValues(rec){if(rec?.schema!==2)rec=null;const d=deriveMetric(rec||{});return{views:fmtCount(rec?.views),likes:fmtCount(rec?.likes),comments:fmtCount(rec?.comments),reposts:fmtCount(rec?.reposts),er:fmtPct(d.er),growth:fmtPct(d.growth,true),multiple:fmtMul(d.multiple),date:shortDate(rec?.postedAt)}}
function gridRows(code){const rec=metricStore[code];if(!rec)return{row1:['','','',''],row2:['','','','']};const v=metricValues(rec);return{row1:[v.views?`▶${v.views}`:'',v.likes?`♥${v.likes}`:'',v.comments?`●${v.comments}`:'',v.reposts?`↻${v.reposts}`:''],row2:[v.er?`ER ${v.er}`:'',v.growth?`24h ${v.growth}`:'',v.multiple||'',v.date||'']}}
function gridAnchors(){return [...document.querySelectorAll('a[href*="/reel/"],a[href*="/reels/"],a[href*="/p/"],a[href*="/tv/"]')].map(a=>{const id=parseHref(a.getAttribute('href')||''),img=a.querySelector('img');if(!id||!img)return null;const w=a.offsetWidth||img.offsetWidth||0,h=a.offsetHeight||img.offsetHeight||0;if(w<70||h<70||w>innerWidth*.52||h>w*1.7)return null;return{a,id}}).filter(Boolean)}
function gridTargetId(){const xs=gridAnchors().map(x=>({...x,r:x.a.getBoundingClientRect()})).filter(x=>x.r.bottom>0&&x.r.top<innerHeight&&x.r.right>0&&x.r.left<innerWidth);if(!xs.length)return null;const cy=innerHeight/2;xs.sort((a,b)=>Math.abs((a.r.top+a.r.bottom)/2-cy)-Math.abs((b.r.top+b.r.bottom)/2-cy));return xs[0]?.id||null}
function renderCardMetrics(ui,code){if(destroyed)return;const rows=gridRows(code),box=ui?.querySelector('.ri98-metrics');if(!box)return;box.hidden=false;const els=box.querySelectorAll('.ri98-row');[rows.row1,rows.row2].forEach((vals,j)=>[...els[j].children].forEach((sp,i)=>{const text=vals[i]||'';if(sp.textContent!==text)sp.textContent=text;sp.classList.toggle('empty',!text)}))}
function removeCardUi(a){a.querySelector(':scope > .ri98-card-ui')?.remove();a.classList.remove('ri98-host')}
function ensureCard(a,id){a.classList.add('ri98-host');let ui=a.querySelector(':scope > .ri98-card-ui');if(!ui){ui=document.createElement('div');ui.className='ri98-card-ui';ui.innerHTML=`<button class="ri98-save" type="button" aria-label="저장">${dlIcon}</button><div class="ri98-metrics"><div class="ri98-row r1"><span></span><span></span><span></span><span></span></div><div class="ri98-row r2"><span></span><span></span><span></span><span></span></div></div>`;a.appendChild(ui);ui.querySelector('.ri98-save').addEventListener('click',onGridSave)}ui.dataset.code=id.code;ui.dataset.kind=id.kind;renderCardMetrics(ui,id.code);const r=a.getBoundingClientRect();if(r.bottom>-innerHeight*.5&&r.top<innerHeight*1.5)queueResolve(id)}
function feedItems(){const out=[];for(const article of document.querySelectorAll('article')){const link=article.querySelector('a[href*="/reel/"],a[href*="/p/"],a[href*="/tv/"]'),id=parseHref(link?.getAttribute('href')||'');if(!id)continue;const media=[...article.querySelectorAll('video,img')].sort((a,b)=>(b.clientWidth*b.clientHeight)-(a.clientWidth*a.clientHeight))[0];if(!media||media.clientWidth<180)continue;out.push({article,id,media})}return out}
function feedTargetId(){const xs=feedItems().map(x=>({...x,r:x.article.getBoundingClientRect()})).filter(x=>x.r.bottom>0&&x.r.top<innerHeight);if(!xs.length)return null;const cy=innerHeight/2;xs.sort((a,b)=>Math.abs((a.r.top+a.r.bottom)/2-cy)-Math.abs((b.r.top+b.r.bottom)/2-cy));return xs[0]?.id||null}
function ensureFeed(){const valid=new Set();for(const {article,id,media} of feedItems()){valid.add(article);article.classList.add('ri98-feed-article');mergeNative(id.code,article);let bar=article.querySelector('.ri98-feed');if(!bar){bar=document.createElement('div');bar.className='ri98-feed';bar.innerHTML='<div class="ri98-feed-title">RI</div><div class="ri98-feed-grid"></div>';const host=media.parentElement||article;host.classList.add('ri98-feed-host');host.appendChild(bar)}bar.dataset.code=id.code;renderResearchGrid(bar.querySelector('.ri98-feed-grid'),metricStore[id.code],true);queueResolve(id)}document.querySelectorAll('article.ri98-feed-article').forEach(a=>{if(!valid.has(a))a.querySelector('.ri98-feed')?.remove()})}
function ensureCards(){frameId=0;ensureQueued=false;if(destroyed)return;const xs=gridAnchors(),valid=new Set(xs.map(x=>x.a));document.querySelectorAll('a.ri98-host').forEach(a=>{if(!valid.has(a))removeCardUi(a)});for(const {a,id} of xs)ensureCard(a,id);ensureFeed();syncSurface()}
function scheduleEnsure(){if(destroyed||ensureQueued)return;ensureQueued=true;frameId=requestAnimationFrame(ensureCards)}
function queueResolve(id){if(destroyed||!id?.code||freshModel(id.code)||pending.has(id.code)||inFlight.has(id.code))return;const rec=metricStore[id.code],failed=failures.get(id.code);if(failed&&Date.now()-failed.at<RETRY_MS)return;if(rec?.schema===2&&Date.now()-Number(rec.apiAt||0)<CACHE_MS)return;pending.add(id.code);queue.push(id);pump()}
function pump(){while(!destroyed&&workers<2&&queue.length){const id=queue.shift();workers++;resolve(id.code,id.kind).catch(()=>{}).finally(()=>{pending.delete(id.code);workers--;if(!destroyed){refreshVisibleMetrics();pump()}})}}
function onGridSave(e){e.preventDefault();e.stopImmediatePropagation();const b=e.currentTarget,a=b.closest('a'),id=parseHref(a?.getAttribute('href')||'');if(id)openGridMenu(id,b)}
function positionMenu(trigger){if(!menu)return;const r=trigger.getBoundingClientRect(),mr=menu.getBoundingClientRect(),bottomLimit=Math.max(120,innerHeight-78);let left=Math.max(6,Math.min(innerWidth-mr.width-6,r.left)),top=r.bottom+6;if(top+mr.height>bottomLimit)top=Math.max(8,r.top-mr.height-6);menu.style.left=`${left}px`;menu.style.top=`${top}px`}
function addMenuButton(label,fn,wide=false){const b=document.createElement('button');b.textContent=label;if(wide)b.className='wide';b.onclick=async e=>{e.preventDefault();e.stopPropagation();const trigger=menu?.__trigger,html=trigger?.innerHTML;closeMenu();try{if(trigger){trigger.innerHTML='<span class="ri98-spinner"></span>';trigger.disabled=true}await fn();live();if(trigger)trigger.textContent='✓'}catch(x){if(!destroyed&&trigger)trigger.textContent=x.name==='AbortError'?'': '!';if(!destroyed&&x.name!=='AbortError')notify(x.message||'저장에 실패했습니다.')}finally{if(trigger&&!destroyed)later(()=>{trigger.innerHTML=html||dlIcon;trigger.disabled=false},1100)}};menu.appendChild(b)}
function openGridMenu(id,trigger){closeMenu();menu=document.createElement('div');menu.id='ri98-menu';menu.__trigger=trigger;document.documentElement.appendChild(menu);const build=m=>{if(destroyed||!menu||menu.__trigger!==trigger||parseHref(trigger.closest?.('a')?.getAttribute('href')||'')?.code&&parseHref(trigger.closest('a').getAttribute('href')).code!==id.code)return;menu.innerHTML='';if(currentId()?.code===m.code)current=m;if(m.type==='carousel')addMenuButton('슬라이드 전체',()=>saveCarousel(m),true);else if(m.type==='photo')addMenuButton('원본 사진',()=>savePhoto(m),true);else{addMenuButton('영상',()=>saveVideo(m));addMenuButton('음원',()=>saveAudio(m));addMenuButton('이미지',()=>saveImage(m));addMenuButton('3개 모두',()=>saveVideoSet(m))}positionMenu(trigger)};const cached=freshModel(id.code);if(cached){build(cached);return}const wait=document.createElement('button');wait.className='wide';wait.disabled=true;wait.textContent='콘텐츠 확인 중';menu.appendChild(wait);positionMenu(trigger);resolve(id.code,id.kind).then(build).catch(()=>{if(menu&&menu.__trigger===trigger)wait.textContent='확인할 수 없음'})}
function closeMenu(){menu?.remove();menu=null}
function modeLabel(){return saveMode==='folder'?(dirHandle?.name?`지정 폴더 · ${dirHandle.name}`:'지정 폴더'):saveMode==='prompt'?'매번 선택':'기본 다운로드'}
function currentRecord(){const id=currentId()?.code;return id?metricStore[id]||null:null}
function researchCells(rec,placeholder='확인중'){const v=metricValues(rec||{});return metricDefs.map(([key,label])=>({key,label,value:v[key]||placeholder,known:!!v[key]}))}
function renderResearchGrid(el,rec,compact=false){if(destroyed||!el)return;setHtml(el,researchCells(rec,compact?'·':'확인중').map(x=>`<div class="${x.known?'known':'pending'}"><span>${x.label}</span><b>${esc(x.value)}</b></div>`).join(''))}
function researchGridHtml(rec,cls=''){return`<div class="ri98-research-grid ${cls}">${researchCells(rec).map(x=>`<div class="${x.known?'known':'pending'}"><span>${x.label}</span><b>${esc(x.value)}</b></div>`).join('')}</div>`}
function activityHtml(){if(activity.state==='idle')return'';return`<div class="ri98-activity ${activity.state==='error'?'error':''}"><span class="dot"></span><div><b>${esc(activity.message)}</b>${activity.detail?`<small>${esc(activity.detail)}</small>`:''}</div></div>`}
function typeLabel(){return current?.type==='video'?'Reel/영상':current?.type==='photo'?'사진':current?.type==='carousel'?'슬라이드':'콘텐츠'}
function headHtml(title,back=false){return`<div class="ri98-head">${back?'<button data-a="back" class="icon">‹</button>':''}<div class="ri98-title">${esc(title)}</div><button data-a="close" class="icon">×</button></div>`}
function contentCompactHtml(){const title=current?`${current.username!=='unknown'?'@'+current.username:'RI'} · ${typeLabel()}`:'RI Research';return`${headHtml(title)}<div class="ri98-compact-body">${researchGridHtml(currentRecord(),'compact')}<div class="ri98-command"><button class="primary" data-a="save">저장</button><span class="mode">${esc(modeLabel())}</span><button data-a="detail">상세</button><button data-a="global" class="icon">•••</button></div>${activityHtml()}</div>`}
function tabBar(){const tabs=[['summary','요약'],['content','콘텐츠'],['comments','댓글'],['analysis','분석'],['media','미디어']];return`<div class="ri98-tabs">${tabs.map(([k,l])=>`<button data-tab="${k}" class="${detailTab===k?'active':''}">${l}</button>`).join('')}</div>`}
function summaryTab(){const r=currentRecord();return`<section class="ri98-section"><h3>성과 지표</h3>${researchGridHtml(r,'summary')}</section><section class="ri98-section"><h3>콘텐츠 정보</h3><div class="ri98-info"><div><span>계정</span><b>${esc(current?.username&&current.username!=='unknown'?'@'+current.username:'확인 중')}</b></div><div><span>유형</span><b>${esc(typeLabel())}</b></div><div><span>Shortcode</span><b>${esc(current?.code||'확인 중')}</b></div><div><span>저장 방식</span><b>${esc(modeLabel())}</b></div></div></section>`}
function stateCard(title,status,desc,items=[]){return`<div class="ri98-research-card"><div class="top"><b>${title}</b><span>${status}</span></div>${desc?`<p>${desc}</p>`:''}${items.length?`<div class="ri98-tags">${items.map(x=>`<span>${x}</span>`).join('')}</div>`:''}</div>`}
function contentTab(){const r=researchRecord(),m=current,busy=k=>researchBusy.has((m?.code||'')+':'+k);return `${researchGridHtml(currentRecord(),'tabtop')}${textCard('본문',r.caption)}${textCard('해시태그 / 언급',[...(r.hashtags||[]),...(r.mentions||[])].join(' '))}<div class="ri98-research-card"><b>음성 · 이 기기에서 인식</b><p>첫 실행 모델 다운로드 · 최대 180초</p>${researchButton('stt','음성 인식',!m||busy('stt')||m.type==='photo')}${researchButton('import-stt','결과 가져오기',!m)}</div>${textCard('음성 결과',r.stt?.text)}${r.stt?.chunks?.length?textCard('시간대별 문장',r.stt.chunks.map(x=>`${timeLabel(x.start)} ~ ${timeLabel(x.end)}  ${x.text}`).join('\n')):''}<div class="ri98-research-card"><b>화면 글자 · 이 기기에서 인식</b><p>영상: 2초 간격 최대 60프레임${m?.type==='carousel'?' · 첫 슬라이드 대상':''}</p>${researchButton('ocr','글자 인식',!m||busy('ocr'))}${researchButton('import-ocr','결과 가져오기',!m)}</div>${textCard('OCR 결과',r.ocr?.text)}${r.ocr?.frames?.length?textCard(r.ocr.coverage||'인식 범위',r.ocr.frames.map(f=>`${timeLabel(f.time)}\n${f.lines.length?f.lines.map(l=>l.text+(l.bbox?` [${l.bbox.x0},${l.bbox.y0}–${l.bbox.x1},${l.bbox.y1}]`:'')).join('\n'):f.text}`).join('\n\n')):''}`}
function commentsTab(){const c=researchRecord().comments,rows=c?.rows||[],counts={};for(const row of rows)for(const label of row.labels||[])counts[label]=(counts[label]||0)+1;return `${researchGridHtml(currentRecord(),'tabtop')}<div class="ri98-research-card">${researchButton('collect-comments','댓글 수집',!current||researchBusy.has(current.code+':comments'))}<p>수집 ${rows.length}개 · 답글 ${rows.reduce((n,x)=>n+(x.replies?.length||0),0)}개${c?.hasMore?' · 추가 미수집 댓글 있음':''}</p><p>답글은 API 미리보기 범위입니다. 분류는 문구 규칙에 따른 결과입니다.</p>${c?.error?`<p>${esc(c.error)}</p>`:''}</div>${textCard('분류',Object.entries(counts).map(([k,v])=>`${k} ${v}`).join(' · '))}${rows.map(c=>textCard('@'+c.username+(c.labels?.length?' · '+c.labels.join(' / '):''),c.text+(c.replies?.length?'\n\n'+c.replies.map(x=>'↳ @'+x.username+' '+x.text).join('\n'):''))).join('')}`}
function analysisTab(){const a=analyzeResearch(researchRecord());return `${researchGridHtml(currentRecord(),'tabtop')}${textCard('분석 기준','수집된 본문·음성·OCR의 문구를 규칙으로 추출합니다. 영상 구성이나 감정을 확정 판정하지 않습니다.')}${textCard('캡션 첫 문장',a.firstCaption)}${textCard('첫 3초 음성',a.speechStart)}${textCard('행동 유도 문구',a.cta.join('\n'))}${textCard('숫자',a.numbers.join(' · '))}${textCard('가격',a.prices.join(' · '))}`}
function mediaTab(){const metrics=researchGridHtml(currentRecord(),'tabtop');if(!current)return metrics+'<div class="ri98-empty">현재 콘텐츠를 확인하고 있습니다.</div>';if(current.type==='video')return metrics+`<div class="ri98-media-card"><div><b>영상</b><span>원본 MP4</span></div><button data-a="video">저장</button></div><div class="ri98-media-card"><div><b>음원</b><span>분리 오디오</span></div><button data-a="audio">저장</button></div><div class="ri98-media-card"><div><b>이미지</b><span>실제 표지 / 0.000초 프레임</span></div><button data-a="image">저장</button></div>`;if(current.type==='photo')return metrics+`<div class="ri98-media-card"><div><b>원본 사진</b><span>최대 해상도</span></div><button data-a="photo">저장</button></div>`;return metrics+`<div class="ri98-media-card"><div><b>슬라이드 전체</b><span>${current.children?.length||''}개 원본 개별 저장</span></div><button data-a="carousel">저장</button></div>`}
function detailBody(){return detailTab==='summary'?summaryTab():detailTab==='content'?contentTab():detailTab==='comments'?commentsTab():detailTab==='analysis'?analysisTab():mediaTab()}
function detailHtml(){const title=current?`${current.username!=='unknown'?'@'+current.username:'RI'} · ${typeLabel()}`:'RI Research';return`${headHtml(title,true)}${tabBar()}<div class="ri98-detail-body">${detailBody()}${activityHtml()}</div>`}
function listRow(icon,title,sub,value,action,disabled=false){return`<button ${disabled?'disabled':''} data-a="${action||''}" class="ri98-list-row"><span class="ri98-row-icon">${icon}</span><span class="ri98-row-copy"><b>${title}</b><small>${sub||''}</small></span>${value?`<span class="ri98-row-value">${esc(value)}</span>`:''}${!disabled&&action?'<span class="ri98-chevron">›</span>':''}</button>`}
function globalHtml(){return`${headHtml('RI 관리',true)}<div class="ri98-list"><div class="ri98-list-label">관리</div>${listRow('⇩','저장','다운로드 위치와 저장 방식',modeLabel(),'storage')}${listRow('▤','데이터','수집된 성과 기록과 history',`${Object.keys(metricStore).length}개`,'data')}${listRow('◎','리서치','댓글 · STT · OCR · 분석','','research')}${listRow('↻','업데이트',`현재 v${V}`,'','update')}<div class="ri98-list-label">시스템</div>${listRow('⎘','진단 복사','현재 상태를 클립보드로','','copy')}${listRow('×','RI 종료','현재 페이지에서 RI 제거','','destroy')}</div>`}
function storageHtml(){return`${headHtml('저장 방식',true)}<div class="ri98-choice-list"><button data-a="default" class="${saveMode==='default'?'active':''}"><div><b>기본 다운로드</b><small>브라우저 기본 다운로드 위치</small></div><span>${saveMode==='default'?'✓':''}</span></button><button data-a="folder" class="${saveMode==='folder'?'active':''}"><div><b>지정 폴더</b><small>${esc(dirHandle?.name||'한 번 지정하면 다시 사용')}</small></div><span>${saveMode==='folder'?'✓':''}</span></button><button data-a="prompt" class="${saveMode==='prompt'?'active':''}" ${typeof showSaveFilePicker!=='function'?'disabled':''}><div><b>매번 선택</b><small>저장할 때 파일 위치 선택</small></div><span>${saveMode==='prompt'?'✓':''}</span></button></div>`}
function dataHtml(){const recs=Object.values(metricStore),snaps=recs.reduce((s,x)=>s+(x.history?.filter(snapshotValid).length||0),0),accounts=new Set(recs.map(x=>x.username).filter(Boolean)).size;return `${headHtml('데이터',true)}<div class="ri98-data-summary"><div><b>${recs.length}</b><span>콘텐츠</span></div><div><b>${snaps}</b><span>검증된 기록</span></div><div><b>${accounts}</b><span>계정</span></div></div><div class="ri98-note">${researchButton('export-json','JSON 내보내기')}${researchButton('export-csv','CSV 내보내기')}<p>${storageWarning?'저장공간 기록 실패: 내보내기로 보관해주세요.':'북마클릿 전용 저장공간입니다.'}</p></div>`}
function researchHtml(){return `${headHtml('리서치',true)}<div class="ri98-list">${listRow('C','댓글','API 제공 범위 수집 · 미리보기 답글','','collect-comments',!current)}${listRow('S','음성 인식','이 기기에서 처리 · 모델 다운로드 · 최대 180초','','stt',!current||current.type==='photo')}${listRow('O','글자 인식','이 기기에서 처리 · 영상 2초 간격 최대 60프레임','','ocr',!current)}${listRow('S','음성 결과 가져오기','SRT / VTT / TXT / JSON','','import-stt',!current)}${listRow('O','OCR 결과 가져오기','TXT / JSON','','import-ocr',!current)}</div>`}
function renderSheet(){if(destroyed||!sheet||sheet.hidden)return;sheet.dataset.mode=sheetMode;sheet.dataset.view=sheetView;let html='';if(sheetView==='content'&&sheetMode==='compact')html=contentCompactHtml();else if(sheetView==='detail')html=detailHtml();else if(sheetView==='global')html=globalHtml();else if(sheetView==='storage')html=storageHtml();else if(sheetView==='data')html=dataHtml();else if(sheetView==='research')html=researchHtml();const top=sheet.querySelector('.ri98-detail-body')?.scrollTop||0;setHtml(sheet,html);const body=sheet.querySelector('.ri98-detail-body');if(body)body.scrollTop=top}
function openSheet(view='content',mode='compact'){sheetView=view;sheetMode=mode;sheet.hidden=false;if(launcher)launcher.hidden=true;closeMenu();renderSheet();scanQuiet()}
function closeSheet(){sheet.hidden=true;if(launcher){launcher.hidden=false;syncSurface()}}
function backSheet(){if(['storage','data','research'].includes(sheetView)){sheetView='global';sheetMode='panel'}else if(sheetView==='global'||sheetView==='detail'){sheetView='content';sheetMode='compact'}renderSheet()}
function openSaveMenu(trigger){const id=currentId();if(id?.code)openGridMenu(id,trigger)}
async function copyDiag(){const text=JSON.stringify({version:V,url:location.href,current:current?{code:current.code,type:current.type,username:current.username}:null,saveMode,activity,metricCount:Object.keys(metricStore).length},null,2);if(!navigator.clipboard?.writeText)throw Error('클립보드가 지원되지 않습니다');await navigator.clipboard.writeText(text);notify('진단을 복사했습니다.')}
async function sheetAct(a,target){try{if(a==='close')closeSheet();else if(a==='back')backSheet();else if(a==='detail'){sheetView='detail';sheetMode='expanded';detailTab='summary';renderSheet()}else if(a==='global'){sheetView='global';sheetMode='panel';renderSheet()}else if(a==='save')openSaveMenu(target);else if(['storage','data','research'].includes(a)){sheetView=a;renderSheet()}else if(a==='video')await saveVideo();else if(a==='audio')await saveAudio();else if(a==='image')await saveImage();else if(a==='photo')await savePhoto();else if(a==='carousel')await saveCarousel();else if(a==='default')setMode('default');else if(a==='folder')await chooseDir();else if(a==='prompt')setMode('prompt');else if(a==='update')await window.__RI_LOADER_REFRESH?.();else if(a==='copy')await copyDiag();else if(a==='destroy')destroy();else if(a==='collect-comments')await collectComments();else if(a==='stt'||a==='ocr')await runResearch(a);else if(a==='import-stt'||a==='import-ocr')importResearch(a.slice(7));else if(a==='export-json'||a==='export-csv')await exportData(a.slice(7))}catch(e){if(e.name!=='AbortError')notify(e.message||'작업을 완료하지 못했습니다.')}}
function notify(msg){if(destroyed||!msg)return;toast?.remove();const el=document.createElement('div');toast=el;el.id='ri98-toast';el.textContent=msg;document.documentElement.appendChild(el);later(()=>{el.remove();if(toast===el)toast=null},2500)}
function currentReelRoot(){const videos=[...document.querySelectorAll('video')].map(v=>({v,r:v.getBoundingClientRect()})).filter(x=>x.r.width>150&&x.r.height>200&&x.r.bottom>0&&x.r.top<innerHeight).sort((a,b)=>(b.r.width*b.r.height)-(a.r.width*a.r.height));let n=videos[0]?.v||null;for(let i=0;n&&i<6;i++,n=n.parentElement){if(n.querySelectorAll?.('button,[role="button"]').length>=3)return n}return videos[0]?.v?.parentElement||null}
function renderReelMetrics(){if(!reelMetrics)return;const id=routeId();if(!id||id.kind!=='reel'){reelMetrics.hidden=true;return}const root=currentReelRoot();mergeNative(id.code,root);const rec=metricStore[id.code];if(!rec){reelMetrics.hidden=false;renderResearchGrid(reelMetrics,null,true);queueResolve(id);return}reelMetrics.hidden=false;renderResearchGrid(reelMetrics,rec,true)}
function refreshVisibleMetrics(){if(destroyed)return;document.querySelectorAll('.ri98-card-ui').forEach(ui=>renderCardMetrics(ui,ui.dataset.code));document.querySelectorAll('.ri98-feed').forEach(bar=>renderResearchGrid(bar.querySelector('.ri98-feed-grid'),metricStore[bar.dataset.code],true));renderReelMetrics();if(!sheet?.hidden)renderSheet()}
function syncSurface(){if(destroyed||!launcher)return;const reel=/^\/reels?(?:\/|$)/i.test(location.pathname);launcher.classList.toggle('reel',reel);renderReelMetrics();const sig=location.pathname+location.search,id=currentId();if(sig!==routeTick||current&&current.code!==id?.code){routeTick=sig;scanEpoch++;current=null;closeMenu();if(id)queueResolve(id);if(!sheet?.hidden)scanQuiet()}else if(!sheet?.hidden&&id?.code&&!current&&!inFlight.has(id.code)&&Date.now()-(failures.get(id.code)?.at||0)>=RETRY_MS)scanQuiet()}
function scanQuiet(){if(destroyed)return;const id=currentId();if(!id?.code){scanEpoch++;current=null;renderSheet();return}if(current?.code!==id.code){current=null;renderSheet()}if(id.kind==='reel')mergeNative(id.code,currentReelRoot());resolveCurrent(false).catch(e=>{if(destroyed||e.name==='AbortError')return;if(currentId()?.code===id.code){current=null;renderSheet()}})}
function injectCss(){if(document.getElementById('ri98-style'))return;const s=document.createElement('style');s.id='ri98-style';s.textContent=`
.ri98-host{position:relative!important}.ri98-card-ui{position:absolute;inset:0;pointer-events:none;overflow:hidden}.ri98-save{position:absolute;left:4px;top:4px;width:25px;height:25px;padding:0;border:1px solid rgba(255,255,255,.48);border-radius:50%;background:rgba(0,0,0,.32);color:#fff;display:grid;place-items:center;pointer-events:auto;box-shadow:0 1px 3px rgba(0,0,0,.32);-webkit-tap-highlight-color:transparent}.ri98-save svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.ri98-save:active{transform:scale(.94);background:rgba(0,0,0,.58)}.ri98-spinner{width:11px;height:11px;border:2px solid rgba(255,255,255,.35);border-top-color:#fff;border-radius:50%;animation:ri98spin .7s linear infinite}@keyframes ri98spin{to{transform:rotate(360deg)}}
.ri98-metrics{position:absolute;left:0;right:0;bottom:0;padding:17px 4px 4px;background:linear-gradient(to bottom,transparent,rgba(0,0,0,.62));pointer-events:none}.ri98-row{position:relative;width:100%;height:11px;white-space:nowrap}.ri98-row span{position:absolute;top:0;height:11px;line-height:11px;overflow:hidden;text-align:center;font-variant-numeric:tabular-nums;letter-spacing:-.45px;padding:0 1px;box-sizing:border-box}.ri98-row.r1 span{color:#fff;font:800 9.5px/11px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;text-shadow:0 1px 2px #000,0 0 3px #000}.ri98-row.r2 span{color:#fff;font:760 8.2px/11px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;text-shadow:0 1px 2px #000,0 0 2px #000}.ri98-row span:nth-child(1){left:0;width:31%;text-align:left}.ri98-row span:nth-child(2){left:31%;width:27%}.ri98-row span:nth-child(3){left:58%;width:21%}.ri98-row span:nth-child(4){left:79%;width:21%;text-align:right}.ri98-row.r2 span:nth-child(1){left:0;width:27%}.ri98-row.r2 span:nth-child(2){left:27%;width:25%}.ri98-row.r2 span:nth-child(3){left:52%;width:24%}.ri98-row.r2 span:nth-child(4){left:76%;width:24%}.ri98-row span.empty{opacity:0}
#ri98-menu{position:fixed;z-index:2147483646;width:172px;padding:5px;border:1px solid rgba(255,255,255,.15);border-radius:14px;background:rgba(18,18,20,.95);box-shadow:0 8px 22px rgba(0,0,0,.34);display:grid;grid-template-columns:1fr 1fr;gap:4px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}#ri98-menu button{height:35px;border:0;border-radius:9px;background:rgba(255,255,255,.07);color:#fff;font:700 10.5px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}#ri98-menu .wide{grid-column:1/-1}
#ri98-launcher{position:fixed;right:12px;bottom:max(88px,calc(env(safe-area-inset-bottom) + 78px));z-index:2147483643;width:36px;height:36px;border:1px solid rgba(255,255,255,.32);border-radius:50%;background:rgba(15,15,16,.56);color:#fff;display:grid;place-items:center;font:850 10px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;box-shadow:0 2px 7px rgba(0,0,0,.34)}#ri98-launcher[hidden]{display:none}#ri98-launcher.reel{left:12px;right:auto;bottom:max(142px,calc(env(safe-area-inset-bottom) + 132px))}
#ri98-reel-metrics{position:fixed;left:10px;right:72px;top:max(10px,env(safe-area-inset-top));z-index:2147483500;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-radius:11px;background:linear-gradient(90deg,rgba(0,0,0,.42),rgba(0,0,0,.20));backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px);pointer-events:none;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;font-variant-numeric:tabular-nums;overflow:hidden}#ri98-reel-metrics[hidden]{display:none}#ri98-reel-metrics>div{height:31px;padding:4px 5px;box-sizing:border-box;display:grid;align-content:center;gap:1px;border-right:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.07)}#ri98-reel-metrics span{font-size:7.2px;font-weight:680;color:rgba(255,255,255,.62)}#ri98-reel-metrics b{font-size:10px;line-height:1;font-weight:820;text-shadow:0 1px 2px #000;white-space:nowrap;overflow:hidden;text-overflow:clip}#ri98-reel-metrics .pending b{opacity:.35}
.ri98-feed-host{position:relative!important}.ri98-feed{position:absolute;left:7px;right:7px;bottom:7px;z-index:7;padding:5px 6px 6px;border-radius:11px;background:rgba(0,0,0,.46);backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px);pointer-events:none;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.ri98-feed-title{font-size:7px;font-weight:850;opacity:.65;margin-bottom:3px}.ri98-feed-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:3px 6px}.ri98-feed-grid div{min-width:0;display:flex;gap:3px;align-items:baseline}.ri98-feed-grid span{font-size:7px;opacity:.55;white-space:nowrap}.ri98-feed-grid b{font-size:9.2px;white-space:nowrap;overflow:hidden;text-overflow:clip}.ri98-feed-grid .pending b{opacity:.25}
#ri98-sheet{position:fixed;z-index:2147483646;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;overflow:hidden;box-shadow:0 -8px 28px rgba(0,0,0,.30);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}#ri98-sheet[hidden]{display:none}#ri98-sheet[data-mode="compact"]{left:6px;right:6px;bottom:max(6px,env(safe-area-inset-bottom));max-height:146px;border:1px solid rgba(255,255,255,.12);border-radius:17px;background:rgba(18,18,20,.94)}#ri98-sheet[data-mode="expanded"]{left:0;right:0;bottom:0;height:auto;max-height:min(78vh,680px);border-top:1px solid rgba(255,255,255,.12);border-radius:20px 20px 0 0;background:rgba(18,18,20,.96);padding-bottom:env(safe-area-inset-bottom)}#ri98-sheet[data-mode="panel"]{left:6px;right:6px;bottom:max(6px,env(safe-area-inset-bottom));height:auto;max-height:min(70vh,600px);border:1px solid rgba(255,255,255,.12);border-radius:17px;background:rgba(18,18,20,.96)}.ri98-head{height:36px;display:flex;align-items:center;gap:4px;padding:0 7px 0 11px;border-bottom:1px solid rgba(255,255,255,.07)}.ri98-title{flex:1;min-width:0;font-size:12px;font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ri98-head button,.ri98-command button{border:0;background:transparent;color:#fff}.ri98-head .icon,.ri98-command .icon{min-width:32px;height:32px;border-radius:10px;font-size:16px}.ri98-compact-body{padding:6px 9px 8px}.ri98-research-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px}.ri98-research-grid>div{min-width:0;padding:6px 5px;border-radius:9px;background:rgba(255,255,255,.052);display:grid;gap:2px}.ri98-research-grid span{font-size:7.4px;color:rgba(255,255,255,.48);white-space:nowrap}.ri98-research-grid b{font-size:10.2px;line-height:1.05;font-weight:820;white-space:nowrap;overflow:hidden;text-overflow:clip}.ri98-research-grid .pending b{font-size:8px;font-weight:650;color:rgba(255,255,255,.28)}.ri98-research-grid.compact>div{padding:4px 4px}.ri98-research-grid.compact b{font-size:9.5px}.ri98-command{display:flex;align-items:center;gap:5px;margin-top:6px}.ri98-command .mode{flex:1;min-width:0;font-size:8px;color:rgba(255,255,255,.40);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ri98-command button{height:32px;padding:0 10px;border-radius:10px;background:rgba(255,255,255,.07);font:720 10.2px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.ri98-command .primary{background:#fff;color:#111;font-weight:840;min-width:70px}.ri98-activity{display:flex;align-items:center;gap:7px;margin-top:5px;padding:5px 7px;border-radius:8px;background:rgba(255,255,255,.055)}.ri98-activity .dot{width:5px;height:5px;border-radius:50%;background:#fff}.ri98-activity div{display:grid}.ri98-activity b{font-size:9px}.ri98-activity small{font-size:8px;color:rgba(255,255,255,.46)}
.ri98-tabs{height:38px;display:flex;align-items:flex-end;gap:1px;padding:0 7px;border-bottom:1px solid rgba(255,255,255,.07);overflow-x:auto}.ri98-tabs button{height:35px;padding:0 10px;border:0;border-bottom:2px solid transparent;background:transparent;color:rgba(255,255,255,.50);font:720 10.5px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}.ri98-tabs button.active{color:#fff;border-bottom-color:#fff}.ri98-detail-body{max-height:calc(78vh - 78px);overflow:auto;padding:9px 11px 14px;overscroll-behavior:contain}.ri98-section+.ri98-section{margin-top:12px}.ri98-section h3{margin:0 0 7px;font-size:9px;color:rgba(255,255,255,.46);letter-spacing:.2px}.ri98-research-grid.summary>div{padding:8px 6px}.ri98-research-grid.summary b{font-size:11px}.ri98-research-grid.tabtop{margin-bottom:10px}.ri98-info{border-top:1px solid rgba(255,255,255,.065)}.ri98-info div{min-height:34px;display:flex;align-items:center;border-bottom:1px solid rgba(255,255,255,.055)}.ri98-info span{flex:1;font-size:9.2px;color:rgba(255,255,255,.44)}.ri98-info b{font-size:10.3px}.ri98-empty{padding:10px 2px;color:rgba(255,255,255,.44);font-size:9.7px}.ri98-research-card{padding:10px 11px;margin-bottom:7px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.03)}.ri98-research-card .top{display:flex;align-items:center}.ri98-research-card .top b{flex:1;font-size:10.8px}.ri98-research-card .top span{font-size:8.7px;color:rgba(255,255,255,.40)}.ri98-research-card p{margin:6px 0 0;color:rgba(255,255,255,.48);font-size:9.2px;line-height:1.45}.ri98-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.ri98-tags span{padding:4px 7px;border-radius:8px;background:rgba(255,255,255,.052);font-size:8.2px;color:rgba(255,255,255,.58)}.ri98-media-card{min-height:48px;display:flex;align-items:center;gap:8px;border-bottom:1px solid rgba(255,255,255,.06)}.ri98-media-card div{flex:1;display:grid;gap:2px}.ri98-media-card b{font-size:10.8px}.ri98-media-card span{font-size:8.8px;color:rgba(255,255,255,.42)}.ri98-media-card button{height:31px;padding:0 10px;border:1px solid rgba(255,255,255,.10);border-radius:9px;background:rgba(255,255,255,.06);color:#fff;font:700 9.8px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif}
.ri98-list{max-height:calc(70vh - 42px);overflow:auto;padding:2px 10px 11px}.ri98-list-label{padding:8px 2px 4px;color:rgba(255,255,255,.34);font-size:8.3px;font-weight:750}.ri98-list-row{width:100%;min-height:46px;padding:0 2px;border:0;border-bottom:1px solid rgba(255,255,255,.055);background:transparent;color:#fff;display:flex;align-items:center;text-align:left;font-family:inherit}.ri98-list-row:disabled{opacity:.40}.ri98-row-icon{width:28px;height:28px;margin-right:9px;border-radius:9px;background:rgba(255,255,255,.052);display:grid;place-items:center;font-size:10.5px;font-weight:800}.ri98-row-copy{flex:1;min-width:0;display:grid;gap:2px}.ri98-row-copy b{font-size:10.8px}.ri98-row-copy small{font-size:8.5px;color:rgba(255,255,255,.41);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ri98-row-value{font-size:9.2px;color:rgba(255,255,255,.46);max-width:100px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ri98-chevron{font-size:18px;color:rgba(255,255,255,.27);margin-left:8px}.ri98-choice-list{padding:6px 10px 11px}.ri98-choice-list button{width:100%;min-height:49px;margin-bottom:6px;padding:0 11px;border:1px solid rgba(255,255,255,.07);border-radius:12px;background:rgba(255,255,255,.028);color:#fff;display:flex;align-items:center;text-align:left}.ri98-choice-list button.active{border-color:rgba(255,255,255,.26);background:rgba(255,255,255,.07)}.ri98-choice-list button div{flex:1;display:grid;gap:2px}.ri98-choice-list b{font-size:10.8px}.ri98-choice-list small{font-size:8.7px;color:rgba(255,255,255,.41)}.ri98-choice-list span{font-size:13px}.ri98-data-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:8px 10px}.ri98-data-summary div{padding:9px 5px;border-radius:10px;background:rgba(255,255,255,.05);display:grid;gap:2px;text-align:center}.ri98-data-summary b{font-size:12px}.ri98-data-summary span{font-size:7.8px;color:rgba(255,255,255,.43)}.ri98-note{margin:0 10px 11px;padding:9px 10px;border-radius:10px;background:rgba(255,255,255,.032);color:rgba(255,255,255,.46);font-size:9.2px;line-height:1.5}
#ri98-sheet .ri98-research-card button,#ri98-sheet .ri98-note button{margin:6px 5px 0 0;padding:7px 10px;border:1px solid #555;border-radius:8px;background:#333;color:#fff;font-size:10px}#ri98-sheet button:disabled{opacity:.4}#ri98-toast{position:fixed;left:50%;top:max(12px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147483647;max-width:82vw;padding:7px 11px;border-radius:13px;background:rgba(20,20,20,.94);color:#fff;font:700 10px/1.3 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Arial,sans-serif;box-shadow:0 4px 14px rgba(0,0,0,.28);pointer-events:none}
`;document.documentElement.appendChild(s)}
function onScroll(){closeMenu();scheduleEnsure();syncSurface()}function onResize(){closeMenu();scheduleEnsure();syncSurface()}
function ui(){injectCss();launcher=document.createElement('button');launcher.id='ri98-launcher';launcher.textContent='RI';launcher.setAttribute('aria-label','RI Research');launcher.onclick=()=>openSheet('content','compact');document.documentElement.appendChild(launcher);reelMetrics=document.createElement('div');reelMetrics.id='ri98-reel-metrics';reelMetrics.hidden=true;document.documentElement.appendChild(reelMetrics);sheet=document.createElement('div');sheet.id='ri98-sheet';sheet.hidden=true;sheet.addEventListener('click',e=>{const tab=e.target?.closest?.('[data-tab]')?.dataset?.tab;if(tab){detailTab=tab;renderSheet();return}const el=e.target?.closest?.('[data-a]');if(el)sheetAct(el.dataset.a,el)});document.documentElement.appendChild(sheet);syncSurface()}
function destroy(){if(destroyed)return;destroyed=true;scanEpoch++;obs?.disconnect();if(frameId)cancelAnimationFrame(frameId);frameId=0;ensureQueued=false;for(const c of controllers)c.abort();for(const id of timers)clearTimeout(id);for(const id of intervals)clearInterval(id);for(const job of [...jobs])job();for(const task of apiTasks.splice(0))task.no(abortError());queue.length=0;pending.clear();
  closeMenu();sheet?.remove();launcher?.remove();toast?.remove();reelMetrics?.remove();document.getElementById('ri98-style')?.remove();document.querySelectorAll('a.ri98-host').forEach(removeCardUi);document.querySelectorAll('.ri98-feed').forEach(x=>x.remove());document.querySelectorAll('.ri98-feed-host,.ri98-feed-article').forEach(x=>x.classList.remove('ri98-feed-host','ri98-feed-article'));window.removeEventListener('scroll',onScroll,true);window.removeEventListener('resize',onResize,true);window.removeEventListener('popstate',scheduleEnsure);if(window[K]===runtime)delete window[K];if(window.__RI_ACTIVE===runtime)delete window.__RI_ACTIVE;
}
const runtime={version:V,ready:false,scan:resolveCurrent,open:openSheet,close:closeSheet,destroy,saveVideo,saveAudio,saveImage,savePhoto,saveCarousel,saveVideoSet,metrics:()=>metricStore};
window[K]=runtime;window.__RI_ACTIVE=runtime;
try{
  ui();restoreDir();ensureCards();scanQuiet();obs=new MutationObserver(onMutations);obs.observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['href','datetime']});window.addEventListener('scroll',onScroll,true);window.addEventListener('resize',onResize,true);window.addEventListener('popstate',scheduleEnsure);
  every(()=>{if(location.pathname+location.search!==routeTick)scheduleEnsure()},700);every(scheduleEnsure,30000);
  installLoader(BRIDGE_URL,false);runtime.ready=true;document.getElementById('__ri_update_btn')?.style.setProperty('display','none','important');
}catch(e){destroy();throw e}
})();
