const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'../bookmarklets/instagram');
const source=fs.readFileSync(path.join(root,'current.js'),'utf8');
const initAt=source.indexOf('\nconst runtime={');
assert.ok(initAt>0);
const names=['normalizeItem','metricFromItem','metricDeep','persistMetric','deriveMetric','nativeMetrics','mergeNative','resolve','resolveCurrent','queueResolve','scanQuiet','currentRecord','parseCompactCount','renderResearchGrid','renderCardMetrics','destroy','savePhoto','saveVideo','saveCarousel','saveVideoSet','copyDiag','scheduleEnsure','ensureCards','onMutations','sameOriginJson','inspectMp4','imageType','addMenuButton','installLoader','parseResearchFile','normalizeResearchResult','analyzeResearch','classifyComment','normalizedComment','parseHref','captureCaption','collectComments'];
const exposed=`\nconst runtime={};window.audit={${names.join(',')},setMenu(m){menu=m},setCurrent(m){current=m},get current(){return current},cache,metricStore,researchStore,queue,failures,inFlight};})();`;
function make(fetchImpl=async()=>json({}),seed={}){
 let now=1750000000000,calls=0,raf=0;const store=new Map(Object.entries(seed)),frames=new Map();
 class Clock extends Date{static now(){return now}}
 const context={window:{addEventListener(){},removeEventListener(){}},Date:Clock,console,Blob,URL,URLSearchParams,AbortController,DOMException,DataView,Uint8Array,TextEncoder,performance:{now:()=>now},crypto:require('node:crypto').webcrypto,
 location:{pathname:'/p/A/',search:'',origin:'https://www.instagram.com',href:'https://www.instagram.com/p/A/'},
 localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},
 document:{querySelectorAll:()=>[],querySelector:()=>null,getElementById:()=>null,createTreeWalker:r=>{let used=false;return {nextNode:()=>used?null:(used=true,{nodeType:3,parentElement:r,textContent:r.textContent||''})}}},NodeFilter:{SHOW_TEXT:4},
 fetch:async(...a)=>{calls++;return fetchImpl(...a)},innerWidth:390,innerHeight:844,navigator:{},
 requestAnimationFrame:f=>{frames.set(++raf,f);return raf},cancelAnimationFrame:id=>frames.delete(id),setTimeout,clearTimeout,setInterval,clearInterval,queueMicrotask};
 vm.createContext(context);vm.runInContext(source.slice(0,initAt)+exposed,context);
 return {context,a:context.window.audit,store,frames,advance:ms=>now+=ms,calls:()=>calls};
}
function json(data){return {ok:true,status:200,json:async()=>data,headers:{get:()=>null}}}
function media(code='A',extra={}){return {code,pk:'123',media_type:2,user:{username:'owner'},play_count:1000,like_count:12345,comment_count:20,repost_count:0,taken_at:1749000000,video_versions:[{url:'https://media.example/video.mp4',width:1080,height:1920}],...extra}}
function turn(){return new Promise(ok=>setImmediate(ok))}
function nativeRoot(text){const root={textContent:text,closest:()=>null,querySelectorAll:()=>[],querySelector:()=>null};return root}
function box(type,...parts){const payload=Buffer.concat(parts);const head=Buffer.alloc(8);head.writeUInt32BE(payload.length+8);head.write(type,4);return Buffer.concat([head,payload])}
function mp4(kinds=['vide','soun']){const tracks=kinds.map(kind=>{const data=Buffer.alloc(12);data.write(kind,8);return box('trak',box('mdia',box('hdlr',data)))});return new Blob([box('ftyp',Buffer.from('isom0000')),box('moov',...tracks),box('mdat',Buffer.alloc(20))],{type:'video/mp4'})}

test('body, loader and SVG bridge parse as JavaScript',()=>{new vm.Script(source);new vm.Script(fs.readFileSync(path.join(root,'bookmarklet-url.txt'),'utf8').replace(/^javascript:/,''));new vm.Script(fs.readFileSync(path.join(root,'bridge-stable.svg'),'utf8').match(/<!\[CDATA\[([\s\S]*?)\]\]>/)[1])});
test('empty response tries fallback instead of caching a photo',async()=>{const h=make(async()=>h.calls()===1?json({data:{}}):json({data:{items:[media()]}}));assert.equal((await h.a.resolve('A')).type,'video');assert.equal(h.calls(),2)});
test('all invalid responses reject without caching',async()=>{const h=make(async()=>json({data:{}}));await assert.rejects(h.a.resolve('A'));assert.equal(h.calls(),3);assert.equal(h.a.cache.size,0)});
test('xdt_shortcode_media wrapper is normalized',async()=>{const h=make(async()=>json({data:{xdt_shortcode_media:media()}}));assert.equal((await h.a.resolve('A')).username,'owner')});
test('wrong shortcode is never accepted',async()=>{const h=make(async()=>json({data:{items:[media('B')]}}));await assert.rejects(h.a.resolve('A'));assert.equal(h.a.cache.size,0)});
test('403 stops fallback and triggers cooldown',async()=>{const h=make(async()=>({ok:false,status:403}));await assert.rejects(h.a.resolve('A'));await assert.rejects(h.a.resolve('A'));assert.equal(h.calls(),1)});
test('same content shares an in-flight request',async()=>{let release;const h=make(()=>new Promise(ok=>release=()=>ok(json({data:{items:[media()]}}))));const a=h.a.resolve('A'),b=h.a.resolve('A');await turn();release();assert.equal(await a,await b);assert.equal(h.calls(),1)});
test('cache refreshes after 10 minutes',async()=>{const h=make(async()=>json({data:{items:[media()]}}));await h.a.resolve('A');h.advance(599999);await h.a.resolve('A');assert.equal(h.calls(),1);h.advance(2);await h.a.resolve('A');assert.equal(h.calls(),2)});
test('background queue refreshes expired cache',async()=>{const h=make(async()=>json({data:{items:[media()]}}));await h.a.resolve('A');h.advance(600001);h.a.queueResolve({code:'A',kind:'reel'});await turn();assert.equal(h.calls(),2)});
test('API concurrency is limited across direct requests',async()=>{let active=0,peak=0;const releases=[];const h=make(()=>new Promise(ok=>{peak=Math.max(peak,++active);releases.push(()=>{active--;ok(json({}))})}));const requests=Array.from({length:5},(_,i)=>h.a.sameOriginJson('/'+i));await turn();assert.equal(peak,2);while(releases.length){releases.shift()();await turn()}await Promise.all(requests);assert.equal(peak,2)});
test('late A response cannot replace route B',async()=>{const releases={};const h=make(url=>new Promise(ok=>{const vars=JSON.parse(new URL(url,'https://www.instagram.com').searchParams.get('variables'));releases[vars.shortcode]=()=>ok(json({data:{items:[media(vars.shortcode)]}}))}));const a=h.a.resolveCurrent();const caught=assert.rejects(a,{name:'AbortError'});h.context.location.pathname='/p/B/';const b=h.a.resolveCurrent();await turn();releases.B();await b;releases.A();await caught;assert.equal(h.a.current.code,'B')});
test('failed new route clears previous model',async()=>{const h=make(async()=>{throw Error('offline')});h.a.setCurrent({code:'A',item:media()});h.context.location.pathname='/p/B/';h.a.scanQuiet();await turn();assert.equal(h.a.current,null)});
test('detail save refuses a model from another route',async()=>{const h=make();h.a.setCurrent({code:'A',item:media()});h.context.location.pathname='/p/B/';await assert.rejects(h.a.saveVideo(),/현재 콘텐츠/);assert.equal(h.calls(),0)});
test('carousel child and commenter likes never become parent metrics',()=>{const h=make();const r=h.a.metricFromItem({code:'A',carousel_media:[{code:'B',play_count:999,like_count:777}],comments:[{like_count:9}],owner:{like_count:8}},'A','p');assert.equal(r.views,undefined);assert.equal(r.likes,undefined)});
test('known nested metric container works and checks identity',()=>{const h=make();assert.equal(h.a.metricDeep({code:'A',metrics:{like_count:5}},['like_count'],'A'),5);assert.equal(h.a.metricDeep({code:'A',media:{code:'B',like_count:5}},['like_count'],'A'),undefined)});
test('GraphQL aggregate count keys and real zero are supported',()=>{const h=make();const r=h.a.metricFromItem({code:'A',edge_media_preview_like:{count:0},edge_media_to_parent_comment:{count:5}},'A','p');assert.equal(r.likes,0);assert.equal(r.comments,5)});
test('exact API value survives rounded native fallback',()=>{const h=make();h.a.persistMetric(h.a.metricFromItem(media(),'A','reel'));h.a.mergeNative('A',nativeRoot('좋아요 1.2만'));assert.equal(h.a.metricStore.A.likes,12345)});
test('count parser requires only the count, not arbitrary parent text',()=>{const h=make();assert.equal(h.a.parseCompactCount('조회 9000 좋아요 123'),undefined);assert.equal(h.a.parseCompactCount('1.2만'),12000)});
test('native likes do not fabricate a views snapshot',()=>{const h=make();h.a.persistMetric(h.a.metricFromItem(media(),'A','reel'));h.advance(24*3600000);h.a.mergeNative('A',nativeRoot('좋아요 1.2만'));assert.equal(h.a.metricStore.A.history.length,1);assert.equal(h.a.deriveMetric(h.a.metricStore.A).growth,undefined)});
test('24h uses verified actual observations',()=>{const h=make();h.a.persistMetric(h.a.metricFromItem(media(),'A','reel'));h.advance(24*3600000);h.a.persistMetric(h.a.metricFromItem(media('A',{play_count:1500}),'A','reel'));assert.equal(h.a.deriveMetric(h.a.metricStore.A).growth,50)});
test('legacy history is excluded',()=>{const h=make();const now=h.context.Date.now();assert.equal(h.a.deriveMetric({views:1500,viewsAt:now,history:[{t:now-86400000,v:1000}]}).growth,undefined)});
test('account baseline uses publication date, not fetch order',()=>{const h=make();for(let i=0;i<20;i++)h.a.metricStore['n'+i]={shortcode:'n'+i,schema:2,username:'owner',views:100,postedAtMs:1749000000000+i,apiAt:1};for(let i=0;i<20;i++)h.a.metricStore['o'+i]={shortcode:'o'+i,schema:2,username:'owner',views:1000,postedAtMs:1700000000000+i,apiAt:999999};assert.equal(h.a.deriveMetric({shortcode:'A',username:'owner',views:200}).multiple,2)});
test('identical data does not rewrite the DOM',()=>{const h=make();let writes=0;const el={set innerHTML(x){writes++}};h.a.renderResearchGrid(el,{views:1000},true);h.a.renderResearchGrid(el,{views:1000},true);assert.equal(writes,1)});
test('own mutations are ignored; native changes schedule one frame',()=>{const h=make();h.a.onMutations([{target:{nodeType:1,closest:()=>({})},type:'childList',addedNodes:[],removedNodes:[]}]);assert.equal(h.frames.size,0);const r={target:{nodeType:1,closest:()=>null},type:'characterData'};h.a.onMutations([r]);h.a.onMutations([r]);assert.equal(h.frames.size,1)});
test('destroy cancels pending frame and prevents rescheduling',()=>{const h=make();h.a.scheduleEnsure();h.a.destroy();assert.equal(h.frames.size,0);h.a.scheduleEnsure();assert.equal(h.frames.size,0)});
test('same version is destroyed when definitions initialize',()=>{const h=make();let count=0;h.context.window.__RISAVE099={destroy(){count++}};vm.runInContext(source.slice(0,initAt)+exposed,h.context);assert.equal(count,1)});
test('valid video requires audio and video tracks',async()=>{const h=make();const result=await h.a.inspectMp4(mp4());assert.equal(result.video,true);assert.equal(result.audio,true);assert.equal((await h.a.inspectMp4(mp4(['vide']))).audio,false)});
test('HTML and truncated MP4 are rejected',async()=>{const h=make();await assert.rejects(h.a.inspectMp4(new Blob(['<html>login error</html>'])));await assert.rejects(h.a.inspectMp4(new Blob([Buffer.from([0,0,0,100,109,111,111,118])])))});
test('image extension comes from bytes',async()=>{const h=make();assert.equal(await h.a.imageType(new Blob([Buffer.from([255,216,255,224])])),'jpg');await assert.rejects(h.a.imageType(new Blob(['error'])))});
test('photo picker is requested before media fetch',async()=>{const order=[];const h=make(async()=>{order.push('fetch');throw Error('expected fixture failure')},{riSaveMode:'prompt'});h.context.showSaveFilePicker=async()=>{order.push('picker');return {name:'IG_A.jpg'}};await assert.rejects(h.a.savePhoto({code:'A',item:{display_url:'https://media.example/photo.jpg'}}));assert.deepEqual(order,['picker','fetch'])});
test('carousel total failure rejects and reports failed count',async()=>{const h=make(async()=>{throw Error('offline')});await assert.rejects(h.a.saveCarousel({code:'A',children:[{display_url:'https://media.example/a.jpg'},{display_url:'https://media.example/b.jpg'}]}),e=>e.name==='PartialSaveError'&&e.done===0&&e.failed===2)});
test('three-item total failure rejects instead of showing success',async()=>{const h=make(async()=>{throw Error('offline')});await assert.rejects(h.a.saveVideoSet({code:'A',item:media()}),e=>e.name==='PartialSaveError'&&e.failed===3)});
test('grid button displays failure when batch fails',async()=>{const h=make(async()=>{throw Error('offline')});let button;const trigger={innerHTML:'save',disabled:false,textContent:''};h.context.document.createElement=()=>({remove(){}});h.context.document.documentElement={appendChild(){}};h.a.setMenu({__trigger:trigger,remove(){},appendChild:b=>button=b});h.a.addMenuButton('all',()=>h.a.saveVideoSet({code:'A',item:media()}));await button.onclick({preventDefault(){},stopPropagation(){}});assert.equal(trigger.textContent,'!');h.a.destroy()});
test('caption and tags are extracted from API content',()=>{const h=make();h.a.captureCaption({code:'A',item:{caption:{text:'첫 문장 #테스트 @sample'}}});assert.equal(h.a.researchStore.A.caption,'첫 문장 #테스트 @sample');assert.equal(h.a.researchStore.A.hashtags[0],'#테스트')});
test('comment collection exposes partial coverage',async()=>{const h=make(async()=>json({comments:[{pk:'1',text:'가격이 얼마인가요?',user:{username:'u'},preview_child_comments:[{pk:'2',text:'답변'}]}],has_more_comments:true,next_min_id:''}));h.a.setCurrent({code:'A',item:media()});await h.a.collectComments();const c=h.a.researchStore.A.comments;assert.equal(c.rows.length,1);assert.equal(c.hasMore,true);assert.ok(c.error);assert.equal(c.rows[0].replies.length,1)});
test('SRT and VTT timestamps survive import',()=>{const h=make();const r=h.a.parseResearchFile('stt','1\n00:00:01,500 --> 00:00:03,000\n안녕하세요\n\n','sample.srt');assert.equal(r.chunks[0].start,1.5);assert.equal(r.chunks[0].end,3);assert.equal(r.text,'안녕하세요')});
test('plain transcript does not invent timestamps',()=>{const h=make();const r=h.a.parseResearchFile('stt','안녕하세요','sample.txt');assert.equal(r.chunks.length,0)});
test('analysis extracts evidence, not invented video structure',()=>{const h=make();const a=h.a.analyzeResearch({caption:'오늘 12,000원입니다. 프로필 링크를 눌러주세요.'});assert.ok(a.prices.includes('12,000원'));assert.equal(a.cta.length,1);assert.equal(a.speechStart,'')});
test('external and malformed hrefs do not become media IDs',()=>{const h=make();assert.equal(h.a.parseHref('https://evil.example/p/A/'),null);assert.equal(h.a.parseHref('/p/A/').code,'A');assert.equal(h.a.parseHref('/p/A/extra'),null)});

function loaderHarness(){const h=make(),listeners=new Map(),nodes=new Map(),scripts=[];let popupURL;const popup={closed:false,close(){this.closed=true}};h.context.alert=()=>{};h.context.addEventListener=(k,fn)=>listeners.set(k,fn);h.context.removeEventListener=k=>listeners.delete(k);h.context.window.open=u=>{popupURL=u;return popup};h.context.document.getElementById=id=>nodes.get(id)||null;h.context.document.createElement=tag=>({tag,style:{setProperty(){}},remove(){},set id(v){this._id=v;nodes.set(v,this)},get id(){return this._id}});h.context.document.documentElement={appendChild:n=>{if(n.tag==='script')scripts.push(n)}};h.a.installLoader('https://raw.githack.com/owner/repo/ref/bridge.svg',false);return {...h,listeners,popup,scripts,getToken:()=>new URL(popupURL).hash.slice(1)}}
test('loader rejects forged origin/source and keeps cache until ready',async()=>{const h=loaderHarness(),work=h.context.window.__RI_LOADER_REFRESH();const token=h.getToken(),data={type:'RI_STABLE_CODE',target:'current.js',token,sha:'a'.repeat(40),code:source};const on=h.listeners.get('message');on({origin:'https://evil.example',source:h.popup,data});on({origin:'https://raw.githack.com',source:{},data});assert.equal(h.scripts.length,0);on({origin:'https://raw.githack.com',source:h.popup,data});await turn();assert.equal(h.scripts.length,1);assert.equal(h.store.has('__RI_STABLE_BODY'),false);h.context.window.__RI_ACTIVE={ready:true,version:'0.9.9'};h.scripts[0].onload();await work;assert.equal(h.store.get('__RI_STABLE_BODY'),source)});
test('loader runtime failure never caches broken code',async()=>{const h=loaderHarness(),work=h.context.window.__RI_LOADER_REFRESH();h.listeners.get('message')({origin:'https://raw.githack.com',source:h.popup,data:{type:'RI_STABLE_CODE',target:'current.js',token:h.getToken(),sha:'a'.repeat(40),code:source}});await turn();h.scripts[0].onload();await work;assert.equal(h.store.has('__RI_STABLE_BODY'),false)});
test('legacy cache cannot contribute to current snapshots',()=>{const h=make();h.a.metricStore.A={shortcode:'A',views:9000,likes:123,history:[{t:1,v:9000}]};h.a.persistMetric({shortcode:'A',source:'native',nativeAt:h.context.Date.now(),likes:12});assert.equal(h.a.metricStore.A.views,undefined);assert.equal(h.a.metricStore.A.history.length,0);assert.equal(h.a.metricStore.A.schema,2)});
test('caption text saying likes is not counted as native likes',()=>{const h=make();const r=h.a.nativeMetrics(nativeRoot('좋아요 500개에 도전해요'));assert.equal(r.likes,undefined)});
function bridgeHarness(origin='https://www.instagram.com'){
 const messages=[],listeners=new Map(),token='a'.repeat(32),element={setAttribute(){},appendChild(){},textContent:''};
 const opener={postMessage:(m,to)=>messages.push({m,to})};
 const context={opener,location:{hash:'#'+token,search:'?mode=research&origin='+encodeURIComponent(origin)},URLSearchParams,Blob,URL,AbortController,setTimeout,clearTimeout,console,
  document:{getElementById:()=>element,documentElement:element,createElementNS:()=>element},
  addEventListener:(key,fn)=>listeners.set(key,fn),window:{AudioContext:class{async decodeAudioData(){throw Error('audio fixture reached')}async close(){}}}};
 vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'bridge-stable.svg'),'utf8').match(/<!\[CDATA\[([\s\S]*?)\]\]>/)[1],context);
 return {messages,listeners,opener,token};
}
test('bridge uses an exact target origin and ignores foreign input',async()=>{const b=bridgeHarness();assert.equal(b.messages[0].m.type,'RI_RESEARCH_READY');assert.equal(b.messages[0].to,'https://www.instagram.com');const on=b.listeners.get('message'),data={type:'RI_RESEARCH_INPUT',token:b.token,kind:'stt',blob:new Blob(['audio']),mediaType:'video'};await on({source:b.opener,origin:'https://evil.example',data});assert.equal(b.messages.length,1);await on({source:{},origin:'https://www.instagram.com',data});assert.equal(b.messages.length,1);await on({source:b.opener,origin:'https://www.instagram.com',data});assert.equal(b.messages.at(-1).m.type,'RI_RESEARCH_ERROR');assert.match(b.messages.at(-1).m.error,/audio fixture/)});
test('bridge refuses an unapproved parent origin',()=>{const b=bridgeHarness('https://evil.example');assert.equal(b.messages.length,0);assert.equal(b.listeners.size,0)});
